"""
One-time enrichment: parse a supplier price-list spreadsheet into catalog
entries matching business_profiles.py's schema, using the shared
core.catalog_classify engine. Deliberately does NOT write directly to
business_profiles.py or the DB — prints a summary and writes a reviewable
Python source file; a human pastes the reviewed result in. This mirrors
import_products.py's "preview first" convention, and matches the design
requirement that a messy/unparseable minority of rows should be skipped
rather than guessed at — auto-committing unreviewed brand-name guesses to
every bar business on the platform is not something to do blindly.

Usage:
    python manage.py enrich_liquor_catalog "UPDATED PRICELIST.xlsx" --out enriched_preview.py
"""
import re
from django.core.management.base import BaseCommand, CommandError

from core.business_profiles import BAR_CATALOG
from core.catalog_classify import detect_name_price_columns, classify_row


def _normalize(name):
    return re.sub(r'\s+', '', name).lower()


class Command(BaseCommand):
    help = 'Parse a supplier price-list spreadsheet into a reviewable LIQUOR_PRICELIST_CATALOG source snippet.'

    def add_arguments(self, parser):
        parser.add_argument('path', type=str, help='Path to the .xlsx price list')
        parser.add_argument('--out', type=str, default='enriched_preview.py', help='Output Python file path')
        parser.add_argument('--sheet', type=str, default=None, help='Worksheet name (defaults to the active/first sheet)')

    def handle(self, *args, **options):
        try:
            import openpyxl
        except ImportError:
            raise CommandError('openpyxl is required to read the spreadsheet.')

        path = options['path']
        try:
            wb = openpyxl.load_workbook(path, data_only=True)
        except FileNotFoundError:
            raise CommandError(f'File not found: {path}')

        ws = wb[options['sheet']] if options.get('sheet') else wb.active
        rows = [list(r) for r in ws.iter_rows(values_only=True)]

        header_idx, name_col, price_col = detect_name_price_columns(rows)
        if header_idx is None or name_col is None or price_col is None:
            raise CommandError('Could not detect a name/price column layout in this sheet.')

        self.stdout.write(f'Detected header row {header_idx + 1}, name column {name_col}, price column {price_col}.')

        existing_names = {_normalize(e['name']) for e in BAR_CATALOG}

        parsed, skipped, duplicates = [], [], []
        category_counts = {}
        for row in rows[header_idx + 1:]:
            raw_name = row[name_col] if name_col < len(row) else None
            raw_price = row[price_col] if price_col < len(row) else None
            if raw_name is None and raw_price is None:
                continue
            entry = classify_row(raw_name, raw_price)
            if not entry:
                skipped.append(raw_name)
                continue
            if _normalize(entry['name']) in existing_names:
                duplicates.append(entry['name'])
                continue
            parsed.append(entry)
            category_counts[entry['category']] = category_counts.get(entry['category'], 0) + 1

        self.stdout.write(self.style.SUCCESS(
            f'Parsed: {len(parsed)}  Skipped (unparseable): {len(skipped)}  '
            f'Duplicates of existing BAR_CATALOG entries: {len(duplicates)}'
        ))
        self.stdout.write(f'Category breakdown: {category_counts}')
        if skipped:
            self.stdout.write('Sample skipped rows:')
            for s in skipped[:10]:
                self.stdout.write(f'  {s!r}')

        out_path = options['out']
        with open(out_path, 'w', encoding='utf-8') as fh:
            fh.write(
                '"""Generated by `python manage.py enrich_liquor_catalog` — REVIEW before\n'
                'pasting into core/business_profiles.py. Append onto BAR_CATALOG, e.g.:\n'
                '    BAR_CATALOG = [...existing hand-curated entries...] + LIQUOR_PRICELIST_CATALOG\n'
                '"""\n\n'
                'LIQUOR_PRICELIST_CATALOG = [\n'
            )
            for entry in parsed:
                fh.write(f'    {entry!r},\n')
            fh.write(']\n')

        self.stdout.write(self.style.SUCCESS(f'Wrote {len(parsed)} entries to {out_path}'))
