# Generated by Django 6.0 on 2025-12-16 03:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_no', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('unit', models.CharField(max_length=50)),
                ('opening_bin_balance', models.IntegerField(default=0)),
                ('opening_physical', models.IntegerField(default=0)),
                ('reorder_quantity', models.IntegerField(default=0)),
                ('reorder_level', models.IntegerField(default=0)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.store')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('doc_no', models.CharField(blank=True, max_length=50)),
                ('type', models.CharField(choices=[('Issue', 'Issue'), ('Receipt', 'Receipt'), ('Loaned', 'Loaned')], max_length=20)),
                ('qty', models.IntegerField()),
                ('department', models.CharField(blank=True, max_length=100)),
                ('running_balance', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item')),
            ],
        ),
    ]
