# Generated by Django 6.0 on 2026-03-22 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('core', '0002_remove_transaction_running_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Business Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.business'),
        ),
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(default='KES', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='item',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='business',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='accounts.business'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.business'),
        ),
        migrations.AddField(
            model_name='store',
            name='suitable_for_types',
            field=models.ManyToManyField(blank=True, related_name='suitable_stores', to='core.businesstype'),
        ),
        migrations.CreateModel(
            name='SubLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sublocations', to='core.county')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('county', 'name')},
            },
        ),
    ]
