# Generated by Django 6.0 on 2026-03-22 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
        ('core', '0003_businesstype_county_item_business_item_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='accounts.business'),
        ),
    ]
