# Generated by Django 6.0 on 2026-03-22 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
        ('core', '0004_alter_store_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='accounts.business'),
        ),
    ]
