# Generated by Django 6.0 on 2026-03-22 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_store_business'),
        ('core', '0006_seed_business_types_counties'),
    ]

    operations = [
    ]
