# Generated by Django 6.0 on 2026-03-23 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_business_sub_location'),
        ('core', '0007_merge_20260323_0202'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcounties', to='core.county')),
            ],
            options={
                'verbose_name_plural': 'Sub Counties',
                'ordering': ['name'],
                'unique_together': {('county', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('sub_county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wards', to='core.subcounty')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('sub_county', 'name')},
            },
        ),
        migrations.DeleteModel(
            name='SubLocation',
        ),
    ]
