# Generated by Django 6.0 on 2026-03-26 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_business_sub_county_business_ward'),
        ('core', '0009_seed_subcounties_and_wards'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='doc_no',
            new_name='invoice_no',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='department',
        ),
        migrations.AddField(
            model_name='transaction',
            name='recipient',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='accounts.business')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
