# Generated by Django 6.0 on 2026-03-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_doc_no_transaction_invoice_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
