# Generated by Django 4.2.29 on 2026-04-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_order_payment_orderline'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_mode',
            field=models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery')], default='pickup', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('cash', 'Cash on Delivery'), ('pickup_pay', 'Pay at Pickup')], default='mpesa', max_length=15),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('transaction', 'Transaction'), ('warning', 'Warning'), ('staff', 'Staff'), ('report', 'Report'), ('info', 'Info'), ('order', 'Order')], default='info', max_length=20),
        ),
    ]
