# Generated by Django 4.2.29 on 2026-04-08 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_userprofile_role'),
        ('core', '0016_riderprofile_order_rider_supplierrelationship'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('deadline', models.DateField(help_text='Last day to submit bids')),
                ('status', models.CharField(choices=[('open', 'Open for Bids'), ('evaluating', 'Evaluating'), ('awarded', 'Awarded'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procurement_requests', to='accounts.business')),
                ('category', models.ForeignKey(blank=True, help_text='Type of supplier needed', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.businesstype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('customer_to_business', 'Customer → Business'), ('business_to_supplier', 'Business → Supplier')], max_length=25)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('rating', models.PositiveSmallIntegerField(help_text='1-5 stars')),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_given', to='accounts.business')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='core.order')),
                ('to_business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_received', to='accounts.business')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('delivery_timeline', models.CharField(help_text='e.g. 3 days, 1 week', max_length=100)),
                ('proposal', models.TextField(help_text='Why you are the best fit')),
                ('score', models.DecimalField(decimal_places=2, default=0, help_text='Auto-calculated composite score (0-100)', max_digits=5)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('shortlisted', 'Shortlisted'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='submitted', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('procurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='core.procurementrequest')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_bids', to='accounts.business')),
            ],
            options={
                'ordering': ['-score', 'amount'],
                'unique_together': {('procurement', 'supplier')},
            },
        ),
        migrations.CreateModel(
            name='SupplierApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_offered', models.TextField(help_text='What products/services can you supply?')),
                ('cover_letter', models.TextField(help_text='Why should this business choose you?')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_applications_sent', to='accounts.business')),
                ('target_business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_applications_received', to='accounts.business')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('applicant', 'target_business')},
            },
        ),
    ]
