# Generated by Django 4.2.29 on 2026-04-08 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_procurementrequest_feedback_supplierbid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderprofile',
            name='vehicle_type',
            field=models.CharField(choices=[('motorcycle', 'Motorcycle 🏍️'), ('bicycle', 'Bicycle 🚲'), ('car', 'Car 🚗'), ('footsubishi', 'Footsubishi (Miguu Niponye) 🚶')], default='motorcycle', max_length=30),
        ),
        migrations.CreateModel(
            name='DeliveryRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rated_by', models.CharField(help_text='Customer name or business owner', max_length=200)),
                ('rating', models.PositiveSmallIntegerField(help_text='1-5 stars')),
                ('on_time', models.BooleanField(default=True, help_text='Was delivery on time?')),
                ('item_condition', models.PositiveSmallIntegerField(default=5, help_text='1-5 condition of items on arrival')),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_rating', to='core.order')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='core.riderprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
