# Generated by Django 4.2.29 on 2026-04-08 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_business_mpesa_paybill_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0018_alter_riderprofile_vehicle_type_deliveryrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='mpesa_phone',
            field=models.CharField(blank=True, help_text='M-Pesa phone number for receiving delivery payments', max_length=20),
        ),
        migrations.CreateModel(
            name='PendingTransactionPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('phone', models.CharField(blank=True, help_text='Payer phone number', max_length=20)),
                ('mpesa_receipt', models.CharField(blank=True, db_index=True, max_length=30)),
                ('payment_channel', models.CharField(blank=True, help_text='till, paybill, pochi, phone', max_length=15)),
                ('status', models.CharField(choices=[('pending', 'Pending — Awaiting Confirmation'), ('confirmed', 'Confirmed — Transaction Logged'), ('dismissed', 'Dismissed')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_prompts', to='accounts.business')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_prompts', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, help_text='Linked transaction once confirmed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompt', to='core.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
