# Generated by GitHub Copilot
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_item_lead_time_days_item_safety_days_purchaseorder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierBidLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.supplierbid')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item')),
            ],
        ),
    ]
