# Generated by Django 6.0.3 on 2026-04-14 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_supplierbidline'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('level1', models.CharField(max_length=120)),
                ('level2', models.CharField(blank=True, max_length=120, null=True)),
                ('level3', models.CharField(blank=True, max_length=120, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.category')),
            ],
            options={
                'ordering': ['level1', 'level2', 'level3'],
            },
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='core.category'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['code'], name='core_catego_code_dc8c14_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['level1'], name='core_catego_level1_e89fc1_idx'),
        ),
    ]
