# Generated by Django 6.0.3 on 2026-04-16 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_business_categories'),
        ('core', '0023_importjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('transaction', 'Transaction'), ('order', 'Order'), ('both', 'Both')], default='both', max_length=20)),
                ('cadence', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10)),
                ('horizon', models.IntegerField(default=30)),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('history', models.JSONField(blank=True, default=list)),
                ('forecast', models.JSONField(blank=True, default=list)),
                ('plot_path', models.CharField(blank=True, max_length=512, null=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='accounts.business')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
    ]
