# Generated by Django 4.2.29 on 2026-05-13 02:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_business_categories'),
        ('core', '0024_forecast'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('labor', 'Labor / Salaries'), ('electricity', 'Electricity Bills'), ('rent', 'Rent'), ('utilities', 'Utilities (Water, Internet)'), ('transport', 'Transport / Logistics'), ('marketing', 'Marketing & Advertising'), ('maintenance', 'Maintenance & Repairs'), ('supplies', 'Office Supplies'), ('tax', 'Taxes & Licenses'), ('other', 'Other')], default='other', max_length=20)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='accounts.business')),
            ],
            options={
                'verbose_name': 'Business Expense',
                'verbose_name_plural': 'Business Expenses',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['business', 'date'], name='core_busine_busines_fb13e1_idx')],
            },
        ),
    ]
