# Generated by Django 4.2.29 on 2026-05-16 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_business_expense_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierbid',
            name='delivery_confirmed_at',
            field=models.DateTimeField(blank=True, help_text='Owner confirmed delivery success', null=True),
        ),
        migrations.AddField(
            model_name='supplierbid',
            name='payment_confirmed_at',
            field=models.DateTimeField(blank=True, help_text='Supplier confirmed payment received', null=True),
        ),
    ]
