# Generated by Django 4.2.29 on 2026-05-18 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_supplierbid_delivery_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('credit', 'Credit / Tab')], default='cash', max_length=20),
        ),
    ]
