# Generated by Django 4.2.29 on 2026-05-19 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_business_categories'),
        ('core', '0029_add_transport_and_miraa_business_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='e.g. 3 Pool Tables, Borehole Drilling Rig, Matatu KBX 123Z', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('category', models.CharField(choices=[('equipment', 'Equipment & Machinery'), ('vehicle', 'Vehicle'), ('property', 'Property / Land'), ('renovation', 'Renovation & Fixtures'), ('license', 'Licenses & Permits'), ('stock', 'Initial Stock / Inventory'), ('technology', 'Technology & Software'), ('other', 'Other')], default='equipment', max_length=20)),
                ('date_acquired', models.DateField(help_text='Date this asset was purchased or cost was incurred')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_investments', to='accounts.business')),
            ],
            options={
                'verbose_name': 'Capital Investment',
                'verbose_name_plural': 'Capital Investments',
                'ordering': ['-date_acquired'],
                'indexes': [models.Index(fields=['business', 'date_acquired'], name='core_capita_busines_bf5275_idx')],
            },
        ),
    ]
