# Generated by Django 4.2.29 on 2026-05-22 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_add_pre_app_profit_and_start_date'),
        ('core', '0030_add_capital_investment_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessTypeRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('micro', 'Micro / Informal'), ('semi', 'Semi-Formal'), ('formal', 'Formal / Regulated')], default='formal', max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Brief explanation of what this is and why it is needed')),
                ('issuing_authority', models.CharField(blank=True, help_text='e.g. County Government, NTSA, PPB', max_length=200)),
                ('approximate_cost', models.CharField(blank=True, help_text='e.g. KES 10,000 annually', max_length=100)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('business_type', models.ForeignKey(blank=True, help_text='Leave blank for universal requirements', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='core.businesstype')),
            ],
            options={
                'verbose_name': 'Business Type Requirement',
                'verbose_name_plural': 'Business Type Requirements',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_declared', models.BooleanField(default=False)),
                ('declared_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional — e.g. permit number, expiry date')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_records', to='accounts.business')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_records', to='core.businesstyperequirement')),
            ],
            options={
                'verbose_name': 'Business Compliance Record',
                'verbose_name_plural': 'Business Compliance Records',
                'ordering': ['requirement__display_order'],
                'unique_together': {('business', 'requirement')},
            },
        ),
    ]
