# Generated by Django 4.2.29 on 2026-05-22 11:37

from django.db import migrations


REQUIREMENTS_MAP = {
    # ── TIER 1: MICRO / INFORMAL ─────────────────────────────────────────────
    'Mama Mboga / Kiosk': {
        'tier': 'micro',
        'requirements': [
            {
                'name': 'County Market Levy (Kanjo Fee)',
                'description': 'Weekly trading fee paid to county officials (Kanjo). '
                               'Amount and collection frequency varies by county. '
                               'Nairobi: ~KES 100/week, collected twice weekly.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'KES 100/week',
                'order': 1,
            },
        ],
    },
    'Kibanda / Food Stall': {
        'tier': 'micro',
        'requirements': [
            {
                'name': 'County Market Levy (Kanjo Fee)',
                'description': 'Weekly trading fee paid to county officials. '
                               'Varies by county and location.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'KES 100–300/week',
                'order': 1,
            },
            {
                'name': 'County Food Hygiene Certificate',
                'description': 'Basic food handling compliance for food-selling stalls.',
                'issuing_authority': 'County Public Health Department',
                'approximate_cost': 'Included in county levy in most areas',
                'order': 2,
            },
        ],
    },
    'Vegetable & Produce Stall': {
        'tier': 'micro',
        'requirements': [
            {
                'name': 'County Market Levy (Kanjo Fee)',
                'description': 'Weekly trading fee paid to county officials.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'KES 100/week',
                'order': 1,
            },
        ],
    },
    'Mkokoteni / Wholesale Distributor': {
        'tier': 'micro',
        'requirements': [
            {
                'name': 'County Market Levy (Kanjo Fee)',
                'description': 'Weekly trading fee for street/market traders.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'KES 100–300/week',
                'order': 1,
            },
        ],
    },
    'Boda Boda Operator': {
        'tier': 'micro',
        'requirements': [
            {
                'name': 'Valid Driving Licence (Class G — Motorcycle)',
                'description': 'A valid NTSA Class G driving licence is the primary '
                               'legal requirement to operate a boda boda.',
                'issuing_authority': 'NTSA (National Transport & Safety Authority)',
                'approximate_cost': 'KES 600–1,000 (licence fee)',
                'order': 1,
            },
            {
                'name': 'County Boda Boda SACCO Registration',
                'description': 'Most counties require boda boda operators to belong '
                               'to a registered SACCO for compliance and insurance.',
                'issuing_authority': 'County Government / SACCO',
                'approximate_cost': 'Varies by SACCO',
                'order': 2,
            },
        ],
    },
    'Tuk-Tuk / Three-Wheeler Services': {
        'tier': 'micro',
        'requirements': [
            {
                'name': 'Valid Driving Licence',
                'description': 'Valid NTSA driving licence for the vehicle class.',
                'issuing_authority': 'NTSA',
                'approximate_cost': 'KES 600–1,000',
                'order': 1,
            },
            {
                'name': 'County Operating Permit',
                'description': 'County-issued permit to operate tuk-tuk services.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'Varies by county',
                'order': 2,
            },
        ],
    },

    # ── TIER 2: SEMI-FORMAL ──────────────────────────────────────────────────
    'Retail Shop': {
        'tier': 'semi',
        'requirements': [
            {
                'name': 'Single Business Permit (SBP)',
                'description': 'Annual county business operating permit. '
                               'Required for all formal retail operations.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'KES 10,000 annually',
                'order': 1,
            },
        ],
    },
    'Cereal & Grain Shop': {
        'tier': 'semi',
        'requirements': [
            {
                'name': 'Single Business Permit (SBP)',
                'description': 'Annual county business operating permit.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'KES 10,000 annually',
                'order': 1,
            },
            {
                'name': 'KEBS Weights & Measures Compliance',
                'description': 'Scales and measuring equipment must be KEBS-certified '
                               'for grain trading.',
                'issuing_authority': 'Kenya Bureau of Standards (KEBS)',
                'approximate_cost': 'KES 2,000–5,000',
                'order': 2,
            },
        ],
    },
    'Airtime & Accessories Shop': {
        'tier': 'semi',
        'requirements': [
            {
                'name': 'Single Business Permit (SBP)',
                'description': 'Annual county business operating permit.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'KES 10,000 annually',
                'order': 1,
            },
        ],
    },
    'Cosmetics & Beauty Supply': {
        'tier': 'semi',
        'requirements': [
            {
                'name': 'Single Business Permit (SBP)',
                'description': 'Annual county business operating permit.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'KES 10,000 annually',
                'order': 1,
            },
            {
                'name': 'KEBS Product Standards Compliance',
                'description': 'Cosmetics sold must meet KEBS standards.',
                'issuing_authority': 'Kenya Bureau of Standards (KEBS)',
                'approximate_cost': 'Varies per product',
                'order': 2,
            },
        ],
    },
    'M-Pesa Agent / Mobile Money': {
        'tier': 'semi',
        'requirements': [
            {
                'name': 'Single Business Permit (SBP)',
                'description': 'Annual county business operating permit.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'KES 10,000 annually',
                'order': 1,
            },
            {
                'name': 'Mobile Money Agent Agreement',
                'description': 'Formal agent agreement with a licensed mobile money '
                               'provider (e.g. Safaricom for M-Pesa).',
                'issuing_authority': 'Safaricom / Mobile Money Provider',
                'approximate_cost': 'No direct cost (float requirement applies)',
                'order': 2,
            },
        ],
    },

    # ── TIER 3: FOOD & BEVERAGE ───────────────────────────────────────────────
    'Restaurant / Hotel': {
        'tier': 'formal',
        'requirements': [
            {
                'name': 'Single Business Permit (SBP)',
                'description': 'Annual county business operating permit.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'KES 10,000–30,000 annually',
                'order': 1,
            },
            {
                'name': 'County Food Hygiene Certificate',
                'description': 'Certifies the premises meets food safety standards.',
                'issuing_authority': 'County Public Health Department',
                'approximate_cost': 'Included in SBP or separate fee',
                'order': 2,
            },
            {
                'name': 'Food Handler Medical Certificates',
                'description': 'All staff handling food must have current medical '
                               'certificates from a county health facility.',
                'issuing_authority': 'County Health Department',
                'approximate_cost': 'KES 500–1,000 per staff member',
                'order': 3,
            },
            {
                'name': 'Fire Safety Certificate',
                'description': 'Annual fire safety inspection and certificate.',
                'issuing_authority': 'County Fire Department',
                'approximate_cost': 'KES 2,000–5,000 annually',
                'order': 4,
            },
        ],
    },
    'Bakery': {
        'tier': 'formal',
        'requirements': [
            {
                'name': 'Single Business Permit (SBP)',
                'description': 'Annual county business operating permit.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'KES 10,000 annually',
                'order': 1,
            },
            {
                'name': 'County Food Hygiene Certificate',
                'description': 'Certifies bakery premises meets food safety standards.',
                'issuing_authority': 'County Public Health Department',
                'approximate_cost': 'Included in SBP or separate fee',
                'order': 2,
            },
            {
                'name': 'Food Handler Medical Certificates',
                'description': 'All food-handling staff require medical certificates.',
                'issuing_authority': 'County Health Department',
                'approximate_cost': 'KES 500–1,000 per staff member',
                'order': 3,
            },
            {
                'name': 'KEBS Certification (packaged products)',
                'description': 'Required if selling packaged/branded baked goods.',
                'issuing_authority': 'Kenya Bureau of Standards (KEBS)',
                'approximate_cost': 'Varies by product',
                'order': 4,
                'mandatory': False,
            },
        ],
    },
    'Coffee Shop / Café': {
        'tier': 'formal',
        'requirements': [
            {
                'name': 'Single Business Permit (SBP)',
                'description': 'Annual county business operating permit.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'KES 10,000 annually',
                'order': 1,
            },
            {
                'name': 'County Food Hygiene Certificate',
                'description': 'Food safety certification for the premises.',
                'issuing_authority': 'County Public Health Department',
                'approximate_cost': 'Included in SBP or separate',
                'order': 2,
            },
            {
                'name': 'Food Handler Medical Certificates',
                'description': 'All staff handling food and beverages.',
                'issuing_authority': 'County Health Department',
                'approximate_cost': 'KES 500–1,000 per staff',
                'order': 3,
            },
            {
                'name': 'Fire Safety Certificate',
                'description': 'Annual fire inspection certificate.',
                'issuing_authority': 'County Fire Department',
                'approximate_cost': 'KES 2,000–5,000',
                'order': 4,
            },
        ],
    },
    'Nyama Choma Joint': {
        'tier': 'formal',
        'requirements': [
            {
                'name': 'Single Business Permit (SBP)',
                'description': 'Annual county business operating permit.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'KES 10,000 annually',
                'order': 1,
            },
            {
                'name': 'County Food Hygiene Certificate',
                'description': 'Food safety certification for meat preparation.',
                'issuing_authority': 'County Public Health Department',
                'approximate_cost': 'Included in SBP or separate',
                'order': 2,
            },
            {
                'name': 'County Veterinary Inspection Certificate',
                'description': 'Confirms meat sourced from inspected animals.',
                'issuing_authority': 'County Veterinary Department',
                'approximate_cost': 'Varies',
                'order': 3,
            },
            {
                'name': 'Food Handler Medical Certificates',
                'description': 'All food-handling staff.',
                'issuing_authority': 'County Health Department',
                'approximate_cost': 'KES 500–1,000 per staff',
                'order': 4,
            },
            {
                'name': 'Fire Safety Certificate',
                'description': 'Annual fire inspection — especially important for '
                               'open-flame cooking operations.',
                'issuing_authority': 'County Fire Department',
                'approximate_cost': 'KES 2,000–5,000',
                'order': 5,
            },
        ],
    },
    'Butchery': {
        'tier': 'formal',
        'requirements': [
            {
                'name': 'Single Business Permit (SBP)',
                'description': 'Annual county business operating permit.',
                'issuing_authority': 'County Government',
                'approximate_cost': '~KES 10,000 annually',
                'order': 1,
            },
            {
                'name': 'County Food Hygiene Certificate',
                'description': 'Certifies the butchery meets food handling standards.',
                'issuing_authority': 'County Public Health Department',
                'approximate_cost': 'Included in consolidated permit',
                'order': 2,
            },
            {
                'name': 'Food Handler Medical Certificates',
                'description': 'All meat-handling staff must have current medical '
                               'certificates.',
                'issuing_authority': 'County Health Department',
                'approximate_cost': 'KES 500–1,000 per staff',
                'order': 3,
            },
            {
                'name': 'Fire Safety Certificate',
                'description': 'Annual fire safety inspection.',
                'issuing_authority': 'County Fire Department',
                'approximate_cost': 'Included in consolidated permit',
                'order': 4,
            },
            {
                'name': 'Pest Control Permit',
                'description': 'Certificate from a licensed pest control company '
                               'confirming premises has been treated.',
                'issuing_authority': 'Licensed Pest Control Company',
                'approximate_cost': 'Included in consolidated permit (~KES 10,000 total)',
                'order': 5,
            },
            {
                'name': 'County Veterinary Inspection Certificate',
                'description': 'Confirms all meat sold comes from inspected and '
                               'approved animals.',
                'issuing_authority': 'County Veterinary Department',
                'approximate_cost': 'Included in consolidated permit',
                'order': 6,
            },
        ],
    },
    'Butchery & Abattoir': {
        'tier': 'formal',
        'requirements': [
            {
                'name': 'Single Business Permit (SBP)',
                'description': 'Annual county business operating permit.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'KES 10,000+ annually',
                'order': 1,
            },
            {
                'name': 'Kenya Meat Commission (KMC) Operating Licence',
                'description': 'Mandatory licence for abattoir operations.',
                'issuing_authority': 'Kenya Meat Commission',
                'approximate_cost': 'Varies by scale',
                'order': 2,
            },
            {
                'name': 'NEMA Environmental Licence',
                'description': 'Mandatory for abattoir waste management compliance.',
                'issuing_authority': 'National Environment Management Authority (NEMA)',
                'approximate_cost': 'KES 10,000–50,000',
                'order': 3,
            },
            {
                'name': 'County Veterinary Inspection Certificate',
                'description': 'Regular veterinary inspection of all animals slaughtered.',
                'issuing_authority': 'County Veterinary Department',
                'approximate_cost': 'Per inspection fee',
                'order': 4,
            },
            {
                'name': 'Food Handler Medical Certificates',
                'description': 'All staff handling meat.',
                'issuing_authority': 'County Health Department',
                'approximate_cost': 'KES 500–1,000 per staff',
                'order': 5,
            },
            {
                'name': 'Fire Safety Certificate',
                'description': 'Annual fire safety inspection.',
                'issuing_authority': 'County Fire Department',
                'approximate_cost': 'KES 2,000–5,000',
                'order': 6,
            },
            {
                'name': 'Pest Control Permit',
                'description': 'Licensed pest control treatment certificate.',
                'issuing_authority': 'Licensed Pest Control Company',
                'approximate_cost': 'KES 3,000–8,000',
                'order': 7,
            },
        ],
    },
    'Liquor Store / Bar': {
        'tier': 'formal',
        'requirements': [
            {
                'name': 'Single Business Permit (SBP)',
                'description': 'Annual county business operating permit.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'Included in consolidated permit',
                'order': 1,
            },
            {
                'name': 'County Liquor / Unified Business Permit',
                'description': 'Primary alcohol trading licence. Covers on-premise '
                               'consumption (bar) or off-premise (liquor store). '
                               'Issued by County Alcoholic Drinks Control Committee. '
                               'Distance restriction: premises must be 300m+ from '
                               'schools, churches, mosques, and hospitals.',
                'issuing_authority': 'County Alcoholic Drinks Control Committee',
                'approximate_cost': 'KES 36,000–40,000 (small bar), '
                                    'KES 50,000–100,000 (large club)',
                'order': 2,
            },
            {
                'name': 'Alcohol Opening Hours Permit',
                'description': 'Permit specifying approved operating hours for '
                               'alcohol service. Hours vary by county.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'Included in consolidated permit',
                'order': 3,
            },
            {
                'name': 'Music Permit',
                'description': 'Required for playing music on premises (live or '
                               'recorded). Issued annually.',
                'issuing_authority': 'Music Copyright Society of Kenya (MCSK) / '
                                     'County Government',
                'approximate_cost': 'KES 5,000–10,000 annually',
                'order': 4,
            },
            {
                'name': 'County Food Hygiene Certificate',
                'description': 'Required if food is served alongside alcohol.',
                'issuing_authority': 'County Public Health Department',
                'approximate_cost': 'Included in consolidated permit',
                'order': 5,
            },
            {
                'name': 'Pest Control Permit',
                'description': 'Licensed pest control treatment certificate.',
                'issuing_authority': 'Licensed Pest Control Company',
                'approximate_cost': 'Included in consolidated permit',
                'order': 6,
            },
            {
                'name': 'Fire Safety Certificate',
                'description': 'Annual fire safety inspection — mandatory for '
                               'premises serving the public.',
                'issuing_authority': 'County Fire Department',
                'approximate_cost': 'Included in consolidated permit',
                'order': 7,
            },
        ],
    },
    'Fish Monger': {
        'tier': 'formal',
        'requirements': [
            {
                'name': 'Single Business Permit (SBP)',
                'description': 'Annual county business operating permit.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'KES 10,000 annually',
                'order': 1,
            },
            {
                'name': 'County Food Hygiene Certificate',
                'description': 'Food safety certification for fish handling.',
                'issuing_authority': 'County Public Health Department',
                'approximate_cost': 'Included in SBP or separate',
                'order': 2,
            },
            {
                'name': 'Kenya Fisheries Service Compliance',
                'description': 'Compliance with fish quality and sourcing standards.',
                'issuing_authority': 'Kenya Fisheries Service (KFS)',
                'approximate_cost': 'Varies',
                'order': 3,
            },
        ],
    },

    # ── TIER 3: HEALTHCARE ───────────────────────────────────────────────────
    'Pharmacy': {
        'tier': 'formal',
        'requirements': [
            {
                'name': 'PPB Retail Pharmacy Premises Licence',
                'description': 'Primary licence for operating a retail pharmacy. '
                               'Premises must be inspected and approved by PPB.',
                'issuing_authority': 'Pharmacy & Poisons Board (PPB)',
                'approximate_cost': 'KES 10,000–20,000 annually',
                'order': 1,
            },
            {
                'name': 'PPB Practising Certificate (Registered Pharmacist)',
                'description': 'A registered pharmacist must be on premises. '
                               'Their PPB practising certificate is mandatory.',
                'issuing_authority': 'Pharmacy & Poisons Board (PPB)',
                'approximate_cost': 'KES 5,000–10,000 annually',
                'order': 2,
            },
            {
                'name': 'Single Business Permit (SBP)',
                'description': 'Annual county business operating permit.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'KES 10,000 annually',
                'order': 3,
            },
        ],
    },
    'Clinic / Hospital': {
        'tier': 'formal',
        'requirements': [
            {
                'name': 'KMPDC Facility Registration',
                'description': 'Mandatory registration of the health facility with '
                               'the Kenya Medical Practitioners & Dentists Council.',
                'issuing_authority': 'Kenya Medical Practitioners & Dentists Council (KMPDC)',
                'approximate_cost': 'Varies by facility type',
                'order': 1,
            },
            {
                'name': 'Ministry of Health Facility Registration',
                'description': 'National registration of the health facility.',
                'issuing_authority': 'Ministry of Health',
                'approximate_cost': 'Varies',
                'order': 2,
            },
            {
                'name': 'Single Business Permit (SBP)',
                'description': 'Annual county business operating permit.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'KES 10,000 annually',
                'order': 3,
            },
            {
                'name': 'NEMA Compliance Certificate',
                'description': 'Environmental compliance for medical waste management.',
                'issuing_authority': 'National Environment Management Authority (NEMA)',
                'approximate_cost': 'Varies',
                'order': 4,
            },
        ],
    },
    'Dental Clinic': {
        'tier': 'formal',
        'requirements': [
            {
                'name': 'KMPDC Registration (Dentist)',
                'description': 'Dentists practicing in Kenya must be registered '
                               'with KMPDC.',
                'issuing_authority': 'Kenya Medical Practitioners & Dentists Council (KMPDC)',
                'approximate_cost': 'Annual practising fee',
                'order': 1,
            },
            {
                'name': 'Single Business Permit (SBP)',
                'description': 'Annual county business operating permit.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'KES 10,000 annually',
                'order': 2,
            },
            {
                'name': 'NEMA Compliance (Dental Waste)',
                'description': 'Compliance for disposing dental waste including '
                               'amalgam and sharps.',
                'issuing_authority': 'NEMA',
                'approximate_cost': 'Varies',
                'order': 3,
            },
        ],
    },
    'Optical / Eye Clinic': {
        'tier': 'formal',
        'requirements': [
            {
                'name': 'Kenya Optometrists & Dispensing Opticians Board Registration',
                'description': 'Practitioners must be registered with the board.',
                'issuing_authority': 'Kenya Optometrists & Dispensing Opticians Board',
                'approximate_cost': 'Annual fee',
                'order': 1,
            },
            {
                'name': 'Single Business Permit (SBP)',
                'description': 'Annual county business operating permit.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'KES 10,000 annually',
                'order': 2,
            },
        ],
    },
    'Agro-Vet Shop': {
        'tier': 'formal',
        'requirements': [
            {
                'name': 'Kenya Veterinary Board Registration',
                'description': 'Mandatory registration for agro-vet businesses '
                               'selling veterinary products.',
                'issuing_authority': 'Kenya Veterinary Board (KVB)',
                'approximate_cost': 'Annual registration fee',
                'order': 1,
            },
            {
                'name': 'PPB Veterinary Medicines Licence',
                'description': 'Required for stocking and selling veterinary '
                               'pharmaceutical products.',
                'issuing_authority': 'Pharmacy & Poisons Board (PPB)',
                'approximate_cost': 'KES 5,000–15,000 annually',
                'order': 2,
            },
            {
                'name': 'Single Business Permit (SBP)',
                'description': 'Annual county business operating permit.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'KES 10,000 annually',
                'order': 3,
            },
            {
                'name': 'KEPHIS Compliance',
                'description': 'Required for stocking crop protection products '
                               '(pesticides, herbicides).',
                'issuing_authority': 'Kenya Plant Health Inspectorate Service (KEPHIS)',
                'approximate_cost': 'Varies',
                'order': 4,
            },
        ],
    },
    'Gym / Fitness Center': {
        'tier': 'formal',
        'requirements': [
            {
                'name': 'Single Business Permit (SBP)',
                'description': 'Annual county business operating permit.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'KES 10,000 annually',
                'order': 1,
            },
            {
                'name': 'County Health Certificate',
                'description': 'Health and sanitation inspection of the facility.',
                'issuing_authority': 'County Public Health Department',
                'approximate_cost': 'Included in SBP or separate',
                'order': 2,
            },
            {
                'name': 'Fire Safety Certificate',
                'description': 'Annual fire safety inspection.',
                'issuing_authority': 'County Fire Department',
                'approximate_cost': 'KES 2,000–5,000',
                'order': 3,
            },
        ],
    },

    # ── TIER 3: TRANSPORT ────────────────────────────────────────────────────
    'Matatu / PSV Owner': {
        'tier': 'formal',
        'requirements': [
            {
                'name': 'NTSA Public Service Vehicle (PSV) Licence',
                'description': 'Mandatory licence for operating a public service '
                               'vehicle.',
                'issuing_authority': 'NTSA',
                'approximate_cost': 'Annual fee',
                'order': 1,
            },
            {
                'name': 'NTSA Route Permit',
                'description': 'Permit specifying the approved route of operation.',
                'issuing_authority': 'NTSA / County Government',
                'approximate_cost': 'Varies by route',
                'order': 2,
            },
            {
                'name': 'PSV Comprehensive Insurance',
                'description': 'Mandatory PSV insurance — standard vehicle insurance '
                               'is insufficient for PSV operations.',
                'issuing_authority': 'Licensed Insurance Provider',
                'approximate_cost': 'Varies by vehicle value',
                'order': 3,
            },
            {
                'name': 'SACCO Membership',
                'description': 'NTSA regulations require matatu operators to belong '
                               'to a registered SACCO.',
                'issuing_authority': 'Registered Matatu SACCO',
                'approximate_cost': 'Varies by SACCO',
                'order': 4,
            },
            {
                'name': 'Annual Vehicle Inspection Certificate',
                'description': 'Annual roadworthiness inspection.',
                'issuing_authority': 'NTSA',
                'approximate_cost': 'KES 1,000–3,000',
                'order': 5,
            },
            {
                'name': 'Speed Limiter & CCTV Installation Certificate',
                'description': 'Mandatory for all PSVs under NTSA regulations.',
                'issuing_authority': 'NTSA-approved installer',
                'approximate_cost': 'KES 5,000–15,000 (one-time)',
                'order': 6,
            },
        ],
    },
    'Ride-Hailing Vehicle Owner (Uber/Bolt/Faras)': {
        'tier': 'formal',
        'requirements': [
            {
                'name': 'NTSA Vehicle Inspection Certificate',
                'description': 'Annual roadworthiness inspection.',
                'issuing_authority': 'NTSA',
                'approximate_cost': 'KES 1,000–3,000',
                'order': 1,
            },
            {
                'name': 'Platform Operator Agreement',
                'description': 'Formal agreement with ride-hailing platform '
                               '(Uber, Bolt, Faras, etc.).',
                'issuing_authority': 'Ride-hailing Platform',
                'approximate_cost': 'No direct cost (commission applies)',
                'order': 2,
            },
            {
                'name': 'PSV Insurance Extension',
                'description': 'Vehicle insurance must include PSV extension for '
                               'commercial passenger carrying.',
                'issuing_authority': 'Licensed Insurance Provider',
                'approximate_cost': 'Varies',
                'order': 3,
            },
        ],
    },
    'Tour & Safari Vehicle Owner': {
        'tier': 'formal',
        'requirements': [
            {
                'name': 'Kenya Tourism Regulatory Authority (KTRA) Licence',
                'description': 'Tour operator licence from KTRA.',
                'issuing_authority': 'Kenya Tourism Regulatory Authority',
                'approximate_cost': 'Annual fee',
                'order': 1,
            },
            {
                'name': 'NTSA Tourist Vehicle Certificate',
                'description': 'Special vehicle classification for tourist transport.',
                'issuing_authority': 'NTSA',
                'approximate_cost': 'Annual fee',
                'order': 2,
            },
            {
                'name': 'Comprehensive Vehicle Insurance',
                'description': 'Full comprehensive insurance with PSV extension.',
                'issuing_authority': 'Licensed Insurance Provider',
                'approximate_cost': 'Varies by vehicle value',
                'order': 3,
            },
        ],
    },
    'Driving School': {
        'tier': 'formal',
        'requirements': [
            {
                'name': 'NTSA Driving School Accreditation',
                'description': 'Mandatory accreditation from NTSA to legally '
                               'offer driving instruction.',
                'issuing_authority': 'NTSA',
                'approximate_cost': 'Annual accreditation fee',
                'order': 1,
            },
            {
                'name': 'Dual-Control Vehicle Certification',
                'description': 'Training vehicles must have dual controls and '
                               'NTSA approval.',
                'issuing_authority': 'NTSA',
                'approximate_cost': 'Vehicle modification cost',
                'order': 2,
            },
            {
                'name': 'NTSA-Certified Driving Instructors',
                'description': 'All instructors must hold NTSA instructor '
                               'certification.',
                'issuing_authority': 'NTSA',
                'approximate_cost': 'Per instructor',
                'order': 3,
            },
            {
                'name': 'Single Business Permit (SBP)',
                'description': 'Annual county business operating permit.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'KES 10,000 annually',
                'order': 4,
            },
        ],
    },

    # ── TIER 3: CONSTRUCTION & TRADES ────────────────────────────────────────
    'Construction': {
        'tier': 'formal',
        'requirements': [
            {
                'name': 'NCA Registration Certificate',
                'description': 'Mandatory registration with the National Construction '
                               'Authority. Operating without NCA registration is illegal '
                               'under the NCA Act 2011.',
                'issuing_authority': 'National Construction Authority (NCA)',
                'approximate_cost': 'Varies by contractor grade (NCA 1–8)',
                'order': 1,
            },
            {
                'name': 'Single Business Permit (SBP)',
                'description': 'Annual county business operating permit.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'KES 10,000 annually',
                'order': 2,
            },
        ],
    },
    'Electrical Contractor': {
        'tier': 'formal',
        'requirements': [
            {
                'name': 'EPRA Electrical Contractor Licence',
                'description': 'Mandatory licence from Energy and Petroleum '
                               'Regulatory Authority for electrical installation work.',
                'issuing_authority': 'Energy & Petroleum Regulatory Authority (EPRA)',
                'approximate_cost': 'Annual fee',
                'order': 1,
            },
            {
                'name': 'NCA Registration (if construction-related)',
                'description': 'NCA registration required when electrical work '
                               'is part of a construction project.',
                'issuing_authority': 'National Construction Authority (NCA)',
                'approximate_cost': 'Varies',
                'order': 2,
                'mandatory': False,
            },
            {
                'name': 'Single Business Permit (SBP)',
                'description': 'Annual county business operating permit.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'KES 10,000 annually',
                'order': 3,
            },
        ],
    },
    'Plumbing Services': {
        'tier': 'formal',
        'requirements': [
            {
                'name': 'County Plumbing Certification',
                'description': 'County-issued certification for plumbing contractors.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'Varies by county',
                'order': 1,
            },
            {
                'name': 'Single Business Permit (SBP)',
                'description': 'Annual county business operating permit.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'KES 10,000 annually',
                'order': 2,
            },
        ],
    },
    'Roofing & Waterproofing': {
        'tier': 'formal',
        'requirements': [
            {
                'name': 'NCA Registration Certificate',
                'description': 'NCA registration for construction-related trades.',
                'issuing_authority': 'National Construction Authority (NCA)',
                'approximate_cost': 'Varies by grade',
                'order': 1,
            },
            {
                'name': 'Single Business Permit (SBP)',
                'description': 'Annual county business operating permit.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'KES 10,000 annually',
                'order': 2,
            },
        ],
    },
    'Tiling & Flooring': {
        'tier': 'formal',
        'requirements': [
            {
                'name': 'NCA Registration Certificate',
                'description': 'NCA registration for construction-related trades.',
                'issuing_authority': 'National Construction Authority (NCA)',
                'approximate_cost': 'Varies by grade',
                'order': 1,
            },
            {
                'name': 'Single Business Permit (SBP)',
                'description': 'Annual county business operating permit.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'KES 10,000 annually',
                'order': 2,
            },
        ],
    },
    'Welding & Fabrication Workshop': {
        'tier': 'formal',
        'requirements': [
            {
                'name': 'Single Business Permit (SBP)',
                'description': 'Annual county business operating permit.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'KES 10,000 annually',
                'order': 1,
            },
            {
                'name': 'Fire Safety Certificate',
                'description': 'Mandatory for welding operations due to fire risk.',
                'issuing_authority': 'County Fire Department',
                'approximate_cost': 'KES 2,000–5,000',
                'order': 2,
            },
            {
                'name': 'NEMA Compliance (Fumes & Waste)',
                'description': 'Compliance for metal waste and fume management.',
                'issuing_authority': 'NEMA',
                'approximate_cost': 'Varies',
                'order': 3,
                'mandatory': False,
            },
        ],
    },

    # ── TIER 3: ENERGY & WATER ───────────────────────────────────────────────
    'Fuel Station': {
        'tier': 'formal',
        'requirements': [
            {
                'name': 'EPRA Fuel Station Licence',
                'description': 'Primary licence for operating a fuel retail station. '
                               'Most important requirement — annual renewal.',
                'issuing_authority': 'Energy & Petroleum Regulatory Authority (EPRA)',
                'approximate_cost': 'Annual fee',
                'order': 1,
            },
            {
                'name': 'NEMA Environmental Impact Assessment (EIA)',
                'description': 'Mandatory environmental assessment for fuel storage '
                               'and operations.',
                'issuing_authority': 'National Environment Management Authority (NEMA)',
                'approximate_cost': 'KES 50,000–200,000',
                'order': 2,
            },
            {
                'name': 'Fire Safety Certificate',
                'description': 'Critical — annual fire safety inspection for fuel '
                               'storage premises.',
                'issuing_authority': 'County Fire Department',
                'approximate_cost': 'KES 5,000–20,000',
                'order': 3,
            },
            {
                'name': 'Single Business Permit (SBP)',
                'description': 'Annual county business operating permit.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'KES 10,000 annually',
                'order': 4,
            },
        ],
    },
    'Borehole Drilling Services': {
        'tier': 'formal',
        'requirements': [
            {
                'name': 'Water Resources Authority (WRA) Drilling Permit',
                'description': 'Mandatory permit for all borehole drilling operations '
                               'in Kenya.',
                'issuing_authority': 'Water Resources Authority (WRA)',
                'approximate_cost': 'KES 10,000–50,000',
                'order': 1,
            },
            {
                'name': 'NEMA Environmental Impact Assessment',
                'description': 'Required for commercial borehole drilling operations.',
                'issuing_authority': 'NEMA',
                'approximate_cost': 'Varies by scale',
                'order': 2,
            },
            {
                'name': 'Water Quality Testing Certificate',
                'description': 'Borehole water must be tested and certified safe.',
                'issuing_authority': 'KEBS / Kenya Water Institute (KEWI)',
                'approximate_cost': 'KES 5,000–20,000 per test',
                'order': 3,
            },
            {
                'name': 'Single Business Permit (SBP)',
                'description': 'Annual county business operating permit.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'KES 10,000 annually',
                'order': 4,
            },
        ],
    },
    'Water Refilling / Dispensing Point': {
        'tier': 'formal',
        'requirements': [
            {
                'name': 'KEBS Water Quality Certification',
                'description': 'Mandatory certification confirming dispensed water '
                               'meets Kenya Bureau of Standards quality requirements.',
                'issuing_authority': 'Kenya Bureau of Standards (KEBS)',
                'approximate_cost': 'KES 10,000–30,000 annually',
                'order': 1,
            },
            {
                'name': 'County Public Health Certificate',
                'description': 'Health and sanitation inspection of the water '
                               'dispensing premises.',
                'issuing_authority': 'County Public Health Department',
                'approximate_cost': 'Included in SBP or separate',
                'order': 2,
            },
            {
                'name': 'Single Business Permit (SBP)',
                'description': 'Annual county business operating permit.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'KES 10,000 annually',
                'order': 3,
            },
            {
                'name': 'Annual Water Quality Testing',
                'description': 'Regular water quality tests to maintain certification.',
                'issuing_authority': 'KEBS / Accredited Lab',
                'approximate_cost': 'KES 3,000–10,000 per test',
                'order': 4,
            },
        ],
    },
    'Solar Panel Installation': {
        'tier': 'formal',
        'requirements': [
            {
                'name': 'EPRA Electrical Contractor Licence',
                'description': 'Required for solar installation involving electrical '
                               'grid connection.',
                'issuing_authority': 'EPRA',
                'approximate_cost': 'Annual fee',
                'order': 1,
            },
            {
                'name': 'Single Business Permit (SBP)',
                'description': 'Annual county business operating permit.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'KES 10,000 annually',
                'order': 2,
            },
        ],
    },

    # ── TIER 3: FINANCIAL SERVICES ───────────────────────────────────────────
    'Forex Bureau': {
        'tier': 'formal',
        'requirements': [
            {
                'name': 'CBK Forex Bureau Licence',
                'description': 'Primary licence from Central Bank of Kenya. '
                               'Minimum paid-up capital of KES 5 million required. '
                               'Annual CBK inspection and renewal.',
                'issuing_authority': 'Central Bank of Kenya (CBK)',
                'approximate_cost': 'Annual licence fee + KES 5M minimum capital',
                'order': 1,
            },
            {
                'name': 'AML/CFT Policy Documentation',
                'description': 'Anti-Money Laundering and Counter-Financing of '
                               'Terrorism policy required by CBK.',
                'issuing_authority': 'Central Bank of Kenya (CBK)',
                'approximate_cost': 'No direct cost (compliance requirement)',
                'order': 2,
            },
            {
                'name': 'Single Business Permit (SBP)',
                'description': 'Annual county business operating permit.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'KES 10,000 annually',
                'order': 3,
            },
        ],
    },
    'Microfinance / SACCO': {
        'tier': 'formal',
        'requirements': [
            {
                'name': 'SASRA Licence (Deposit-Taking SACCOs)',
                'description': 'Mandatory licence from SACCO Societies Regulatory '
                               'Authority for deposit-taking operations.',
                'issuing_authority': 'SACCO Societies Regulatory Authority (SASRA)',
                'approximate_cost': 'Annual licence fee',
                'order': 1,
            },
            {
                'name': 'Annual Returns to SASRA',
                'description': 'Annual financial returns submission to SASRA.',
                'issuing_authority': 'SASRA',
                'approximate_cost': 'No direct cost (compliance)',
                'order': 2,
            },
            {
                'name': 'Single Business Permit (SBP)',
                'description': 'Annual county business operating permit.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'KES 10,000 annually',
                'order': 3,
            },
        ],
    },
    'Insurance Agency': {
        'tier': 'formal',
        'requirements': [
            {
                'name': 'IRA Insurance Agent Licence',
                'description': 'Mandatory licence from Insurance Regulatory '
                               'Authority to sell insurance products.',
                'issuing_authority': 'Insurance Regulatory Authority (IRA)',
                'approximate_cost': 'Annual licence fee',
                'order': 1,
            },
            {
                'name': 'Insurance Company Appointment Letter',
                'description': 'Formal appointment from a licensed insurer '
                               'authorising you to sell their products.',
                'issuing_authority': 'Licensed Insurance Company',
                'approximate_cost': 'No direct cost',
                'order': 2,
            },
            {
                'name': 'Single Business Permit (SBP)',
                'description': 'Annual county business operating permit.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'KES 10,000 annually',
                'order': 3,
            },
        ],
    },
    'Betting Shop / Gaming': {
        'tier': 'formal',
        'requirements': [
            {
                'name': 'BCLB Betting Control Licence',
                'description': 'National licence from Betting Control & Licensing '
                               'Board. Required before any betting operations begin.',
                'issuing_authority': 'Betting Control & Licensing Board (BCLB)',
                'approximate_cost': 'Annual licence fee (varies by type)',
                'order': 1,
            },
            {
                'name': 'County Entertainment Permit',
                'description': 'County-issued permit for operating entertainment '
                               'and gaming premises.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'Varies by county',
                'order': 2,
            },
            {
                'name': 'Age Verification System',
                'description': 'Documented system for verifying customers are 18+. '
                               'Mandatory under BCLB regulations.',
                'issuing_authority': 'BCLB',
                'approximate_cost': 'System/signage cost',
                'order': 3,
            },
            {
                'name': 'KRA Excise Duty Registration',
                'description': 'Registration for excise duty compliance on '
                               'betting/gaming revenue.',
                'issuing_authority': 'Kenya Revenue Authority (KRA)',
                'approximate_cost': 'No direct cost (compliance)',
                'order': 4,
            },
            {
                'name': 'Single Business Permit (SBP)',
                'description': 'Annual county business operating permit.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'KES 10,000 annually',
                'order': 5,
            },
        ],
    },

    # ── TIER 3: REAL ESTATE ──────────────────────────────────────────────────
    'Real Estate Agency / Realtor': {
        'tier': 'formal',
        'requirements': [
            {
                'name': 'Estate Agents Registration Board (EARB) Licence',
                'description': 'Mandatory licence under the Estate Agents Act '
                               'Cap 533. Operating without EARB registration is '
                               'illegal.',
                'issuing_authority': 'Estate Agents Registration Board (EARB)',
                'approximate_cost': 'Annual registration fee',
                'order': 1,
            },
            {
                'name': 'Single Business Permit (SBP)',
                'description': 'Annual county business operating permit.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'KES 10,000 annually',
                'order': 2,
            },
        ],
    },
    'Property Management': {
        'tier': 'formal',
        'requirements': [
            {
                'name': 'EARB Licence or Arrangement with Licensed Agent',
                'description': 'Property managers must either hold an EARB licence '
                               'or operate under a licensed estate agent.',
                'issuing_authority': 'Estate Agents Registration Board (EARB)',
                'approximate_cost': 'Annual fee',
                'order': 1,
            },
            {
                'name': 'Single Business Permit (SBP)',
                'description': 'Annual county business operating permit.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'KES 10,000 annually',
                'order': 2,
            },
        ],
    },
    'Real Estate Developer': {
        'tier': 'formal',
        'requirements': [
            {
                'name': 'NCA Registration Certificate',
                'description': 'Mandatory NCA registration for construction and '
                               'development activities.',
                'issuing_authority': 'National Construction Authority (NCA)',
                'approximate_cost': 'Varies by grade',
                'order': 1,
            },
            {
                'name': 'NEMA Environmental Impact Assessment',
                'description': 'Mandatory for all new construction/development '
                               'projects.',
                'issuing_authority': 'NEMA',
                'approximate_cost': 'Varies by project scale',
                'order': 2,
            },
            {
                'name': 'County Planning & Building Approval',
                'description': 'Architectural plans must be approved by county '
                               'planning department before construction.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'Varies by project',
                'order': 3,
            },
            {
                'name': 'Single Business Permit (SBP)',
                'description': 'Annual county business operating permit.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'KES 10,000 annually',
                'order': 4,
            },
        ],
    },
    'Rental Properties / Landlord': {
        'tier': 'semi',
        'requirements': [
            {
                'name': 'Single Business Permit (SBP)',
                'description': 'County business permit for rental income activities.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'KES 10,000 annually',
                'order': 1,
            },
            {
                'name': 'KRA Rental Income Tax Compliance',
                'description': 'Rental income must be declared to KRA. '
                               'Monthly rental income tax (MRI) applies.',
                'issuing_authority': 'Kenya Revenue Authority (KRA)',
                'approximate_cost': 'No direct cost (tax compliance)',
                'order': 2,
            },
            {
                'name': 'County Rates Clearance Certificate',
                'description': 'Proof that land rates are up to date — required '
                               'for legal rental operations.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'Rates amount varies by property',
                'order': 3,
            },
        ],
    },

    # ── TIER 3: SECURITY ─────────────────────────────────────────────────────
    'Security Services': {
        'tier': 'formal',
        'requirements': [
            {
                'name': 'PSRA Operating Licence',
                'description': 'Mandatory licence from Private Security Regulatory '
                               'Authority. Operating without PSRA registration is '
                               'a criminal offence.',
                'issuing_authority': 'Private Security Regulatory Authority (PSRA)',
                'approximate_cost': 'Annual licence fee',
                'order': 1,
            },
            {
                'name': 'National Police Service Vetting (Guards)',
                'description': 'All security guards must be vetted by the NPS.',
                'issuing_authority': 'National Police Service (NPS)',
                'approximate_cost': 'Per guard',
                'order': 2,
            },
            {
                'name': 'Single Business Permit (SBP)',
                'description': 'Annual county business operating permit.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'KES 10,000 annually',
                'order': 3,
            },
        ],
    },

    # ── TIER 3: AGRICULTURE ──────────────────────────────────────────────────
    'Dairy Farm': {
        'tier': 'formal',
        'requirements': [
            {
                'name': 'Kenya Dairy Board (KDB) Licence',
                'description': 'Mandatory licence for commercial milk production '
                               'and processing.',
                'issuing_authority': 'Kenya Dairy Board (KDB)',
                'approximate_cost': 'Annual licence fee',
                'order': 1,
            },
            {
                'name': 'County Public Health Certificate',
                'description': 'Health and sanitation inspection of dairy facilities.',
                'issuing_authority': 'County Public Health Department',
                'approximate_cost': 'Included in SBP or separate',
                'order': 2,
            },
            {
                'name': 'Veterinary Health Certificate (Herd)',
                'description': 'Regular veterinary inspection of dairy animals.',
                'issuing_authority': 'Kenya Veterinary Board',
                'approximate_cost': 'Per inspection',
                'order': 3,
            },
            {
                'name': 'KEBS Milk Quality Standards Compliance',
                'description': 'Milk must meet KEBS quality standards.',
                'issuing_authority': 'Kenya Bureau of Standards (KEBS)',
                'approximate_cost': 'Testing fees',
                'order': 4,
            },
        ],
    },
    'Poultry Farm': {
        'tier': 'formal',
        'requirements': [
            {
                'name': 'Kenya Veterinary Board Compliance',
                'description': 'Veterinary compliance for poultry health management.',
                'issuing_authority': 'Kenya Veterinary Board',
                'approximate_cost': 'Annual inspection fee',
                'order': 1,
            },
            {
                'name': 'KEPHIS Registration',
                'description': 'Kenya Plant Health Inspectorate Service registration '
                               'for poultry feed compliance.',
                'issuing_authority': 'KEPHIS',
                'approximate_cost': 'Annual fee',
                'order': 2,
            },
            {
                'name': 'Single Business Permit (SBP)',
                'description': 'Annual county business operating permit.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'KES 10,000 annually',
                'order': 3,
            },
        ],
    },
    'Fish Farm / Aquaculture': {
        'tier': 'formal',
        'requirements': [
            {
                'name': 'Kenya Fisheries Service Licence',
                'description': 'Licence for commercial fish farming operations.',
                'issuing_authority': 'Kenya Fisheries Service',
                'approximate_cost': 'Annual licence fee',
                'order': 1,
            },
            {
                'name': 'Water Resources Authority (WRA) Permit',
                'description': 'Water abstraction permit for fish farm water use.',
                'issuing_authority': 'Water Resources Authority (WRA)',
                'approximate_cost': 'Annual fee',
                'order': 2,
            },
            {
                'name': 'Single Business Permit (SBP)',
                'description': 'Annual county business operating permit.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'KES 10,000 annually',
                'order': 3,
            },
        ],
    },
    'Greenhouse / Horticulture': {
        'tier': 'formal',
        'requirements': [
            {
                'name': 'KEPHIS Phytosanitary Certificate',
                'description': 'Essential for export of fresh produce. '
                               'KEPHIS inspection and certification required.',
                'issuing_authority': 'Kenya Plant Health Inspectorate Service (KEPHIS)',
                'approximate_cost': 'Per consignment for export',
                'order': 1,
            },
            {
                'name': 'NEMA Compliance (Agrochemicals)',
                'description': 'Environmental compliance for agrochemical use '
                               'in greenhouse operations.',
                'issuing_authority': 'NEMA',
                'approximate_cost': 'Varies',
                'order': 2,
            },
            {
                'name': 'Single Business Permit (SBP)',
                'description': 'Annual county business operating permit.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'KES 10,000 annually',
                'order': 3,
            },
        ],
    },
    'Flower Farm': {
        'tier': 'formal',
        'requirements': [
            {
                'name': 'KEPHIS Phytosanitary Certificate',
                'description': 'Mandatory for cut flower exports.',
                'issuing_authority': 'KEPHIS',
                'approximate_cost': 'Per consignment',
                'order': 1,
            },
            {
                'name': 'Kenya Flower Council Certification',
                'description': 'Industry certification for quality and sustainability '
                               'standards in flower farming.',
                'issuing_authority': 'Kenya Flower Council',
                'approximate_cost': 'Annual membership fee',
                'order': 2,
            },
            {
                'name': 'Water Resources Authority Permit',
                'description': 'Water use permit for irrigation.',
                'issuing_authority': 'WRA',
                'approximate_cost': 'Annual fee',
                'order': 3,
            },
        ],
    },

    # ── TIER 3: EDUCATION ────────────────────────────────────────────────────
    'School / College': {
        'tier': 'formal',
        'requirements': [
            {
                'name': 'Ministry of Education Registration',
                'description': 'Mandatory national registration for all educational '
                               'institutions.',
                'issuing_authority': 'Ministry of Education',
                'approximate_cost': 'Registration fee varies',
                'order': 1,
            },
            {
                'name': 'County Education Office Approval',
                'description': 'County-level approval for the institution.',
                'issuing_authority': 'County Education Office',
                'approximate_cost': 'Varies',
                'order': 2,
            },
            {
                'name': 'TSC Registration (for certified teachers)',
                'description': 'Teachers Service Commission registration required '
                               'for employing certified teachers.',
                'issuing_authority': 'Teachers Service Commission (TSC)',
                'approximate_cost': 'Per teacher',
                'order': 3,
            },
            {
                'name': 'Fire Safety Certificate',
                'description': 'Mandatory fire safety inspection for educational '
                               'premises.',
                'issuing_authority': 'County Fire Department',
                'approximate_cost': 'KES 2,000–5,000',
                'order': 4,
            },
        ],
    },

    # ── TIER 3: POOL & ENTERTAINMENT ────────────────────────────────────────
    'Pool & Snooker Joint': {
        'tier': 'formal',
        'requirements': [
            {
                'name': 'Single Business Permit (SBP)',
                'description': 'Annual county business operating permit.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'KES 10,000 annually',
                'order': 1,
            },
            {
                'name': 'County Entertainment / Gaming Permit',
                'description': 'Required for operating entertainment/gaming '
                               'equipment on premises.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'Varies by county',
                'order': 2,
            },
            {
                'name': 'Fire Safety Certificate',
                'description': 'Annual fire safety inspection.',
                'issuing_authority': 'County Fire Department',
                'approximate_cost': 'KES 2,000–5,000',
                'order': 3,
            },
        ],
    },
    'Cyber Cafe / Printing Shop': {
        'tier': 'semi',
        'requirements': [
            {
                'name': 'Single Business Permit (SBP)',
                'description': 'Annual county business operating permit.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'KES 10,000 annually',
                'order': 1,
            },
            {
                'name': 'Communications Authority Compliance',
                'description': 'Compliance with CA regulations for internet '
                               'service provision.',
                'issuing_authority': 'Communications Authority of Kenya (CA)',
                'approximate_cost': 'Varies',
                'order': 2,
            },
        ],
    },
    'Salon & Barbershop': {
        'tier': 'semi',
        'requirements': [
            {
                'name': 'Single Business Permit (SBP)',
                'description': 'Annual county business operating permit.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'KES 10,000 annually',
                'order': 1,
            },
            {
                'name': 'County Health Certificate',
                'description': 'Health and sanitation inspection of the salon.',
                'issuing_authority': 'County Public Health Department',
                'approximate_cost': 'Included in SBP or separate',
                'order': 2,
            },
        ],
    },
    'Laundry / Dry Cleaning': {
        'tier': 'semi',
        'requirements': [
            {
                'name': 'Single Business Permit (SBP)',
                'description': 'Annual county business operating permit.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'KES 10,000 annually',
                'order': 1,
            },
            {
                'name': 'NEMA Compliance (Chemical Waste)',
                'description': 'Environmental compliance for dry cleaning chemicals.',
                'issuing_authority': 'NEMA',
                'approximate_cost': 'Varies',
                'order': 2,
                'mandatory': False,
            },
        ],
    },
    'Car Wash': {
        'tier': 'semi',
        'requirements': [
            {
                'name': 'Single Business Permit (SBP)',
                'description': 'Annual county business operating permit.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'KES 10,000 annually',
                'order': 1,
            },
            {
                'name': 'NEMA Compliance (Wastewater)',
                'description': 'Car wash wastewater must be properly managed to '
                               'avoid environmental violations.',
                'issuing_authority': 'NEMA',
                'approximate_cost': 'Varies',
                'order': 2,
            },
        ],
    },
    'Auto Garage / Mechanic': {
        'tier': 'semi',
        'requirements': [
            {
                'name': 'Single Business Permit (SBP)',
                'description': 'Annual county business operating permit.',
                'issuing_authority': 'County Government',
                'approximate_cost': 'KES 10,000 annually',
                'order': 1,
            },
            {
                'name': 'NEMA Compliance (Oil & Waste)',
                'description': 'Proper disposal of oil, batteries, and automotive '
                               'waste required.',
                'issuing_authority': 'NEMA',
                'approximate_cost': 'Varies',
                'order': 2,
            },
            {
                'name': 'Fire Safety Certificate',
                'description': 'Mandatory for garages handling flammable materials.',
                'issuing_authority': 'County Fire Department',
                'approximate_cost': 'KES 2,000–5,000',
                'order': 3,
            },
        ],
    },
}


def populate_requirements(apps, schema_editor):
    BusinessType = apps.get_model('core', 'BusinessType')
    BusinessTypeRequirement = apps.get_model('core', 'BusinessTypeRequirement')

    for bt_name, data in REQUIREMENTS_MAP.items():
        try:
            bt = BusinessType.objects.get(name=bt_name)
        except BusinessType.DoesNotExist:
            continue  # skip if business type not found

        tier = data.get('tier', 'formal')
        for i, req in enumerate(data.get('requirements', [])):
            BusinessTypeRequirement.objects.get_or_create(
                business_type=bt,
                name=req['name'],
                defaults={
                    'tier':              tier,
                    'description':       req.get('description', ''),
                    'issuing_authority': req.get('issuing_authority', ''),
                    'approximate_cost':  req.get('approximate_cost', ''),
                    'is_mandatory':      req.get('mandatory', True),
                    'display_order':     req.get('order', i),
                },
            )


def remove_requirements(apps, schema_editor):
    pass  # intentionally irreversible


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_add_business_compliance_models'),
    ]

    operations = [
        migrations.RunPython(populate_requirements, remove_requirements),
    ]
