# Generated by Django 6.0.3 on 2026-05-27 09:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_add_missing_compliance_requirements'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_date', models.DateField(default=django.utils.timezone.now)),
                ('delivery_note_no', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='core.purchaseorder')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-received_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GoodsReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.IntegerField(default=0)),
                ('actual_unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('update_cost_price', models.BooleanField(default=False, help_text="Tick to update this item's cost price to the actual delivery price.")),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('po_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_lines', to='core.purchaseorderline')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.goodsreceipt')),
            ],
        ),
    ]
