# Generated by Django 6.0.3 on 2026-05-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_goods_receipts'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_yield_item',
            field=models.BooleanField(default=False, help_text='Enable if this item loses weight/volume during processing (e.g. butchery cuts, keg pints).'),
        ),
        migrations.AddField(
            model_name='item',
            name='yield_factor',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Fraction of received quantity that becomes usable stock (e.g. 0.65 = 65% yield).', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Receipt', 'Receipt'), ('Issue', 'Issue'), ('Wastage', 'Wastage')], max_length=20),
        ),
    ]
