# Generated by Django 6.0.3 on 2026-05-28 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_yield_based_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='core.county'),
        ),
    ]
