# Generated by Django 6.0.3 on 2026-06-02 07:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_debt_tracker_and_targets'),
        ('core', '0036_add_county_to_customer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='credit_approved',
            field=models.BooleanField(default=False, help_text='Is this customer approved to buy on credit?'),
        ),
        migrations.AddField(
            model_name='customer',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum outstanding credit balance allowed (KES).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='expected_payment_days',
            field=models.PositiveIntegerField(blank=True, help_text='Expected days this customer takes to pay. Cannot exceed the business credit window.', null=True),
        ),
        migrations.CreateModel(
            name='CustomerDebtPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa')], default='cash', max_length=10)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_debt_payments', to='accounts.business')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_payments', to='core.customer')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debt_payments_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Debt Payment',
                'verbose_name_plural': 'Customer Debt Payments',
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='RevenueTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_targets', to='accounts.business')),
                ('store', models.ForeignKey(blank=True, help_text='Leave blank for a business-wide target.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revenue_targets', to='core.store')),
            ],
            options={
                'verbose_name': 'Revenue Target',
                'verbose_name_plural': 'Revenue Targets',
                'ordering': ['target_type'],
                'unique_together': {('business', 'target_type', 'store')},
            },
        ),
    ]
