# Generated by Django 6.0.3 on 2026-06-03 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_add_onboarding_sections_seen'),
        ('core', '0037_debt_tracker_and_targets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_restricted',
            field=models.BooleanField(default=False, help_text='Staff require owner approval to sell this item.'),
        ),
        migrations.AddField(
            model_name='item',
            name='restriction_notes',
            field=models.CharField(blank=True, help_text='Reason for restriction — visible to owner only. e.g. Reserved for special customer, Do not sell until market day.', max_length=200),
        ),
        migrations.CreateModel(
            name='ItemSaleApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('recipient', models.CharField(blank=True, max_length=200)),
                ('invoice_no', models.CharField(blank=True, max_length=50)),
                ('payment_method', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Owner Approval'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=10)),
                ('denial_reason', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_approvals', to='accounts.business')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_approval_decisions', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_approvals', to='core.item')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_approval_requests', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval', to='core.transaction')),
            ],
            options={
                'verbose_name': 'Item Sale Approval',
                'verbose_name_plural': 'Item Sale Approvals',
                'ordering': ['-requested_at'],
            },
        ),
    ]
