# Generated by Django 6.0.3 on 2026-06-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_restricted_items_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='restricted_quantity',
            field=models.PositiveIntegerField(default=0, help_text='Reserve this many units. Staff can freely sell above this threshold. Set to 0 to require approval for ALL sales of this item.'),
        ),
    ]
