# Generated by Django 6.0.3 on 2026-06-06 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_add_restricted_quantity_to_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_produce',
            field=models.BooleanField(default=False, help_text='Enable portion-based selling. Owner defines price presets (e.g. KES 40 = quarter head). Used for vegetables, produce, and gorogoro items.'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='qty',
            field=models.DecimalField(decimal_places=4, help_text='Signed quantity. Negative for Issue/Wastage, positive for Receipt. Supports fractional values for produce items.', max_digits=10),
        ),
        migrations.CreateModel(
            name='ItemPortionPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Display name shown to staff. e.g. "Quarter head", "4 stems", "Small gorogoro"', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Amount the customer pays (KES).', max_digits=8)),
                ('quantity_consumed', models.DecimalField(decimal_places=4, help_text='Stock units consumed. For fractional items: 0.25 = quarter head. For count items: 4 = four stems.', max_digits=8)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first. Use to sort presets by ascending price.')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portion_presets', to='core.item')),
            ],
            options={
                'verbose_name': 'Item Portion Preset',
                'verbose_name_plural': 'Item Portion Presets',
                'ordering': ['display_order', 'price'],
            },
        ),
    ]
