# Generated by Django 6.0.3 on 2026-06-07 15:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_greens_bunch_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='revenue_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.70'), help_text='Default markup used to pre-fill a bunch target from its market cost (1.70 → a 40/= bunch targets 68/=). Overridable per bunch by eye.', max_digits=4),
        ),
        migrations.AlterField(
            model_name='producebunch',
            name='target_revenue',
            field=models.DecimalField(decimal_places=2, help_text='Total money this bunch must give before it is finished. Pre-filled from cost × the item multiplier; override per bunch by eye.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sale_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual cash taken for this sale line. Set for produce / bunch portion sales where the price is NOT selling_price × qty. Preferred by revenue().', max_digits=10, null=True),
        ),
    ]
