# Generated by Django 6.0.3 on 2026-06-13 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_offline_sales_backdated_txn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produceoverhead',
            name='bunch',
            field=models.ForeignKey(blank=True, help_text='Optional link to a specific batch/bunch this cost relates to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='overheads', to='core.producebunch'),
        ),
    ]
