# Generated by Django 6.0.3 on 2026-06-13 15:43

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_add_waitress_role'),
        ('core', '0048_alter_produceoverhead_bunch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TableOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_label', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending — waiting at bar'), ('ACCEPTED', 'Accepted — being prepared'), ('READY', 'Ready for pickup'), ('SERVED', 'Served — delivered to table'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('credit', 'Credit / Tab')], default='cash', max_length=10)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('served_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_orders', to='accounts.business')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_orders', to='core.shift')),
                ('waitress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_orders_placed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Table Order',
                'verbose_name_plural': 'Table Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TableOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=8)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preset_label', models.CharField(blank=True, max_length=60)),
                ('item_name', models.CharField(blank=True, max_length=120)),
                ('notes', models.CharField(blank=True, max_length=100)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='table_order_items', to='core.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.tableorder')),
                ('preset', models.ForeignKey(blank=True, help_text='For keg/portion items — the cup size / portion preset ordered.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_order_items', to='core.itemportionpreset')),
            ],
            options={
                'verbose_name': 'Table Order Item',
                'verbose_name_plural': 'Table Order Items',
                'ordering': ['id'],
            },
        ),
    ]
