# Generated by Django 6.0.3 on 2026-06-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_table_order_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemportionpreset',
            name='is_jug',
            field=models.BooleanField(default=False, help_text='Tick for jug servings — tracks jugs_dispensed on the barrel separately from cups.'),
        ),
        migrations.AddField(
            model_name='kegbarrel',
            name='jugs_dispensed',
            field=models.PositiveIntegerField(default=0, help_text='Running count of jug servings poured. Incremented by record_sale when preset.is_jug is True.'),
        ),
        migrations.AlterField(
            model_name='kegbarrel',
            name='cups_dispensed',
            field=models.PositiveIntegerField(default=0, help_text='Running count of cup servings poured. Incremented by record_sale when preset.is_jug is False.'),
        ),
    ]
