# Generated by Django 6.0.3 on 2026-06-14 19:55

from django.db import migrations, models


def migrate_is_jug_to_serving_type(apps, schema_editor):
    ItemPortionPreset = apps.get_model('core', 'ItemPortionPreset')
    ItemPortionPreset.objects.filter(is_jug=True).update(serving_type='jug')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_jug_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemportionpreset',
            name='serving_type',
            field=models.CharField(choices=[('cup', '☕ Cup / Kikombe'), ('pint', '🍺 Pint'), ('jug', '🫙 Jug')], default='cup', help_text="For keg presets: how this serving is counted in daily reports. 'cup' for kikombe/shots, 'pint' for pints, 'jug' for jugs.", max_length=10),
        ),
        migrations.AddField(
            model_name='kegbarrel',
            name='pints_dispensed',
            field=models.PositiveIntegerField(default=0, help_text='Running count of pint servings poured.'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='keg_qty',
            field=models.PositiveIntegerField(blank=True, help_text='Number of servings in this keg pour (qty is in ml; keg_qty is the human count).', null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='keg_serving',
            field=models.CharField(blank=True, default='', help_text="For keg pours: 'cup', 'pint', or 'jug'. Empty for non-keg transactions.", max_length=10),
        ),
        migrations.AlterField(
            model_name='itemportionpreset',
            name='is_jug',
            field=models.BooleanField(default=False, help_text='Legacy flag — superseded by serving_type. Kept for backward compat.'),
        ),
        migrations.RunPython(migrate_is_jug_to_serving_type, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='kegbarrel',
            name='jugs_dispensed',
            field=models.PositiveIntegerField(default=0, help_text='Running count of jug servings poured.'),
        ),
    ]
