# Generated by Django 6.0.3 on 2026-06-14 20:08

from django.db import migrations


def backfill_serving_type(apps, schema_editor):
    """Set serving_type on existing presets whose label contains 'jug' or 'pint'."""
    ItemPortionPreset = apps.get_model('core', 'ItemPortionPreset')
    to_update = []
    for preset in ItemPortionPreset.objects.filter(serving_type='cup'):
        label_lower = (preset.label or '').lower()
        if 'jug' in label_lower:
            preset.serving_type = 'jug'
            to_update.append(preset)
        elif 'pint' in label_lower:
            preset.serving_type = 'pint'
            to_update.append(preset)
    if to_update:
        ItemPortionPreset.objects.bulk_update(to_update, ['serving_type'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_serving_type_pints_keg_serving'),
    ]

    operations = [
        migrations.RunPython(backfill_serving_type, migrations.RunPython.noop),
    ]
