# Generated by Django 6.0.3 on 2026-06-14 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_recurring_expense'),
        ('core', '0052_backfill_serving_type_from_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('labor', 'Labor / Salaries'), ('electricity', 'Electricity Bills'), ('rent', 'Rent'), ('utilities', 'Utilities (Water, Internet)'), ('transport', 'Transport / Logistics'), ('marketing', 'Marketing & Advertising'), ('maintenance', 'Maintenance & Repairs'), ('supplies', 'Office Supplies'), ('tax', 'Taxes & Licenses'), ('other', 'Other')], default='other', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('period', models.CharField(choices=[('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly (every 3 months)'), ('ANNUAL', 'Annual (yearly)')], default='MONTHLY', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('last_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('last_notified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_expenses', to='accounts.business')),
                ('staff_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_entries', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Recurring Expense',
                'verbose_name_plural': 'Recurring Expenses',
                'ordering': ['category', 'description'],
            },
        ),
    ]
