# Generated by Django 6.0.3 on 2026-06-15 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Expiry date for this stock-in batch. Set on Receipt transactions only.', null=True),
        ),
    ]
