# Generated by Django 6.0.3 on 2026-06-17 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_expiry_date_on_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftStockCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_count', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_counts', to='core.item')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_counts_recorded', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_counts', to='core.shift')),
            ],
            options={
                'verbose_name': 'Shift Stock Count',
                'verbose_name_plural': 'Shift Stock Counts',
                'ordering': ['item__description'],
                'unique_together': {('shift', 'item')},
            },
        ),
    ]
