# Generated by Django 6.0.3 on 2026-06-17 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_prompt_receipt_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingtransactionprompt',
            name='receipt',
            field=models.ForeignKey(blank=True, help_text='Receipt issued at confirmation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompts', to='core.receipt'),
        ),
    ]
