# Generated by Django 6.0.3 on 2026-06-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_deduplicate_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='bartab',
            name='source',
            field=models.CharField(choices=[('bar', 'Bar'), ('kitchen', 'Kitchen')], default='bar', max_length=10),
        ),
        migrations.AddField(
            model_name='store',
            name='is_kitchen',
            field=models.BooleanField(default=False, help_text='Kitchen / grill side venture — separate POS board'),
        ),
    ]
