# Generated by Django 6.0.3 on 2026-06-22 21:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_userprofile_cross_module_access'),
        ('core', '0062_kitchen_store_bartab_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PettyCash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(choices=[('electricity', 'Electricity / Tokens'), ('supplies', 'Supplies (tissues, serviettes, etc.)'), ('transport', 'Transport / Delivery'), ('fuel', 'Fuel / Gas'), ('food', 'Staff Meal'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, max_length=200)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='petty_cash_entries', to='accounts.business')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_cash_recorded', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_cash_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Petty Cash Entry',
                'verbose_name_plural': 'Petty Cash Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
