# Generated by Django 6.0.3 on 2026-06-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_petty_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='source',
            field=models.CharField(blank=True, default='', help_text="'kitchen' for kitchen board sales; '' for bar/quick-sell/debt payments.", max_length=20),
        ),
    ]
