# Generated by Django 6.0.3 on 2026-06-25 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_receipt_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='bottle_envelope',
            field=models.BooleanField(default=False, help_text='Track this item as a bottle/spirits envelope — shift stock counts compute per-bottle revenue variance so shrinkage is in KES, not just units.'),
        ),
        migrations.AddField(
            model_name='item',
            name='tot_ml',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Serving size in ml (e.g. 25 ml for a single tot of spirits). Combined with volume_ml to derive tots_per_unit automatically if not set.', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='tots_per_unit',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Number of servings per bottle/unit (e.g. 30 tots from 750 ml @ 25 ml each). Used to convert unit variance to expected KES loss.', max_digits=6, null=True),
        ),
    ]
