# Generated by Django 6.0.3 on 2026-06-25 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_item_bottle_envelope'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='etims_receipt_no',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='receipt',
            name='etims_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='etims_url',
            field=models.URLField(blank=True, default='', max_length=300),
        ),
    ]
