# Generated by Django 6.0.3 on 2026-06-26 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_receipt_etims_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdebtpayment',
            name='source',
            field=models.CharField(choices=[('bar', 'Bar'), ('kitchen', 'Kitchen')], default='bar', help_text="Which sub-ledger this payment settles. Kitchen staff post 'kitchen'; bar/general staff post 'bar'.", max_length=10),
        ),
    ]
