# Generated by Django 6.0.3 on 2026-06-26 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_customerdebtpayment_source_backfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='source',
            field=models.CharField(choices=[('bar', 'Bar'), ('kitchen', 'Kitchen')], default='bar', help_text="Counter source: 'bar' or 'kitchen'. Drives per-counter cross-check in Z-report.", max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='store',
            field=models.ForeignKey(blank=True, help_text='Which store/counter received this payment (for per-counter M-Pesa reconciliation).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.store'),
        ),
        migrations.AddField(
            model_name='store',
            name='daraja_consumer_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='store',
            name='daraja_consumer_secret',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='store',
            name='daraja_environment',
            field=models.CharField(blank=True, help_text="Leave blank to inherit from business. Set 'sandbox' or 'production' to override.", max_length=10),
        ),
        migrations.AddField(
            model_name='store',
            name='daraja_passkey',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='store',
            name='has_own_mpesa',
            field=models.BooleanField(default=False, help_text='This counter receives M-Pesa on its own Till/Paybill, separate from the business default.'),
        ),
        migrations.AddField(
            model_name='store',
            name='mpesa_paybill',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='store',
            name='mpesa_paybill_account',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='store',
            name='mpesa_pochi',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='store',
            name='mpesa_till',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
