# Generated by Django 6.0.3 on 2026-06-27 03:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_barcuplog_business_level'),
        ('core', '0073_receipt_meta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='barcuplog',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cup_logs', to='core.item'),
        ),
        migrations.AddField(
            model_name='barcuplog',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cup_logs_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='barcuplog',
            name='barrel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cup_logs', to='core.kegbarrel'),
        ),
        migrations.AlterField(
            model_name='barcuplog',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cup_logs', to='accounts.business'),
        ),
    ]
