# Generated by Django 6.0.3 on 2026-06-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_recurringexpense_pay_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='kitchen_cart',
            field=models.JSONField(blank=True, help_text='Serialised cart for kitchen STK push server-side settlement.', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='kitchen_settled',
            field=models.BooleanField(default=False, help_text='True once kitchen_cart has been processed (by callback or JS poll).'),
        ),
    ]
