# Generated by Django 6.0.3 on 2026-06-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_payment_kitchen_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='auto_closed',
            field=models.BooleanField(default=False, help_text='True when the shift was closed automatically by the business-hours sweep.'),
        ),
    ]
