# Generated by Django 6.0.3 on 2026-06-29 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_shift_auto_closed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='recorded_by',
            field=models.ForeignKey(blank=True, help_text='The staff member or owner who recorded this transaction. Null for async/system-generated transactions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
