# Generated by Django 6.0.3 on 2026-06-29 18:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_performer_session'),
        ('core', '0079_transaction_recorded_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessexpense',
            name='category',
            field=models.CharField(choices=[('labor', 'Labor / Salaries'), ('electricity', 'Electricity Bills'), ('rent', 'Rent'), ('utilities', 'Utilities (Water, Internet)'), ('transport', 'Transport / Logistics'), ('marketing', 'Marketing & Advertising'), ('maintenance', 'Maintenance & Repairs'), ('supplies', 'Office Supplies'), ('tax', 'Taxes & Licenses'), ('entertainment', 'Entertainment / DJ / MC Fees'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='category',
            field=models.CharField(choices=[('labor', 'Labor / Salaries'), ('electricity', 'Electricity Bills'), ('rent', 'Rent'), ('utilities', 'Utilities (Water, Internet)'), ('transport', 'Transport / Logistics'), ('marketing', 'Marketing & Advertising'), ('maintenance', 'Maintenance & Repairs'), ('supplies', 'Office Supplies'), ('tax', 'Taxes & Licenses'), ('entertainment', 'Entertainment / DJ / MC Fees'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('performer_type', models.CharField(choices=[('DJ', 'DJ'), ('MC', 'MC'), ('BOTH', 'DJ & MC')], default='DJ', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('genre', models.CharField(blank=True, help_text='e.g. Afrobeats, House, Gospel', max_length=50)),
                ('contract_type', models.CharField(choices=[('ONE_OFF', 'Per session (one-off)'), ('RETAINER', 'Monthly retainer')], default='ONE_OFF', max_length=10)),
                ('standard_rate', models.DecimalField(decimal_places=2, default=0, help_text='Per-session fee (ONE_OFF) or monthly rate (RETAINER)', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performers', to='accounts.business')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PerformerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING_APPROVAL', 'Pending owner approval'), ('ACTIVE', 'Active / in progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled / no-show')], default='ACTIVE', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('agreed_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Unpaid'), ('PAID', 'Paid')], default='PENDING', max_length=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa')], default='cash', max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('staff_rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('staff_notes', models.TextField(blank=True)),
                ('performer_checked_in', models.BooleanField(default=False)),
                ('performer_checkin_at', models.DateTimeField(blank=True, null=True)),
                ('checkin_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('feedback_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performer_sessions', to='accounts.business')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performer_sessions_created', to=settings.AUTH_USER_MODEL)),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.businessexpense')),
                ('performer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='core.performer')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performer_sessions', to='core.shift')),
            ],
            options={
                'ordering': ['-date', '-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('comment', models.TextField(blank=True, max_length=200)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_feedback', to='core.performersession')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
