# Generated by Django 6.0.3 on 2026-07-01 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_performersession_scheduled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performersession',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled / upcoming'), ('PENDING_APPROVAL', 'Pending owner approval'), ('ACTIVE', 'Active / in progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled / no-show')], default='ACTIVE', max_length=20),
        ),
    ]
