# Generated by Django 6.0.3 on 2026-07-01 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_alter_performersession_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performerfeedback',
            name='ip_hash',
        ),
    ]
