# Generated by Django 6.0.3 on 2026-07-05 02:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_can_authorize_tab_accumulation'),
        ('core', '0088_performersession_per_performer_end'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='dob',
            field=models.DateField(blank=True, help_text='Date of birth — used for birthday promotions.', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes about this customer (e.g. preferences, contact details).'),
        ),
        migrations.CreateModel(
            name='PromoMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, help_text='Short internal label for this promo (not sent to customer).', max_length=120)),
                ('message', models.TextField(help_text='The text sent to customers.')),
                ('segment', models.CharField(choices=[('all', 'Wateja Wote'), ('debtors', 'Wadeni Tu'), ('tab_customers', 'Wateja wa Tab'), ('regulars', 'Wateja wa Kawaida (waliokuja ≥3×)'), ('birthday', 'Siku ya Kuzaliwa (wiki hii)'), ('custom', 'Nambari Maalum')], default='all', max_length=20)),
                ('custom_phones', models.TextField(blank=True, help_text='Comma-separated phone numbers for SEGMENT_CUSTOM.')),
                ('channel', models.CharField(choices=[('sms', 'SMS tu'), ('in_app', 'In-App tu'), ('both', 'SMS + In-App')], default='sms', max_length=10)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_messages', to='accounts.business')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
