# Generated by Django 4.2.29 on 2026-07-05 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0091_payment_tab_entry_ids_qs_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='bartab',
            name='tab_receipt_token',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
