# Generated by Django 6.0.3 on 2026-07-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_bar_tab_receipt_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kitchenconsumablelog',
            name='consumable_type',
            field=models.CharField(choices=[('KHAKI_SMALL', '1/4 Khaki bags'), ('KHAKI_LARGE', '1/2 Khaki bags'), ('SAUCE_TOMATO', 'Tomato sauce (jerrican)'), ('OIL_COOKING', 'Cooking Oil (litres)'), ('OTHER', 'Other')], max_length=16),
        ),
        migrations.AlterField(
            model_name='kitchenconsumablelog',
            name='qty',
            field=models.DecimalField(decimal_places=1, help_text='Units bought: pieces for khaki, jerricans for sauce, litres for oil.', max_digits=8),
        ),
    ]
