# Generated by Django 6.0.3 on 2026-07-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_alter_kitchenconsumablelog_consumable_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Receipt', 'Receipt'), ('Issue', 'Issue'), ('Wastage', 'Wastage'), ('OwnerConsumption', 'Owner Consumption')], max_length=20),
        ),
    ]
