# Generated by Django 6.0.3 on 2026-07-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0094_alter_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt_token',
            field=models.CharField(blank=True, db_index=True, help_text='Receipt token for customer-initiated STK push from public receipt page.', max_length=100),
        ),
    ]
