# Generated by Django 6.0.3 on 2026-07-09 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_bartab_void_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='debt_customer',
            field=models.ForeignKey(blank=True, help_text='Customer FK for staff-initiated debt STK Push from the debt tracker page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stk_payments', to='core.customer'),
        ),
    ]
