# Generated by Django 6.0.3 on 2026-07-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0097_payment_debt_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bartab',
            name='source',
            field=models.CharField(choices=[('bar', 'Bar'), ('kitchen', 'Kitchen'), ('qs', 'Quick Sell')], default='bar', max_length=10),
        ),
    ]
