# Generated by Django 6.0.3 on 2026-07-12 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_alter_userprofile_role'),
        ('core', '0101_salary_payment_partial_support'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringexpense',
            name='category',
            field=models.CharField(choices=[('labor', 'Labor / Salaries'), ('electricity', 'Electricity Bills'), ('rent', 'Rent'), ('utilities', 'Utilities (Water, Internet)'), ('transport', 'Transport / Logistics'), ('marketing', 'Marketing & Advertising'), ('maintenance', 'Maintenance & Repairs'), ('supplies', 'Office Supplies'), ('tax', 'Taxes & Licenses'), ('entertainment', 'Entertainment / DJ / MC Fees'), ('security', 'Security & Facilitation'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='salarydeduction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='writeoffrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='StockTake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('reconciled', 'Reconciled')], default='submitted', max_length=20)),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_takes', to='accounts.business')),
                ('conducted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_takes_conducted', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_takes', to='core.shift')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_takes', to='core.store')),
            ],
            options={
                'ordering': ['-taken_at'],
            },
        ),
        migrations.CreateModel(
            name='StockVarianceQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name_cache', models.CharField(max_length=200)),
                ('book_balance', models.DecimalField(decimal_places=3, max_digits=12)),
                ('actual_count', models.DecimalField(decimal_places=3, max_digits=12)),
                ('direction', models.CharField(choices=[('decrease', 'Decrease'), ('increase', 'Increase')], max_length=10)),
                ('estimated_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Staff Response'), ('responded', 'Staff Responded'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('response_type', models.CharField(blank=True, choices=[('cash', 'Cash sale'), ('mpesa', 'M-Pesa sale'), ('credit', 'Credit / Deni sale'), ('receipt', 'Unrecorded receipt'), ('no_internet', 'No internet at the time'), ('unknown', 'Unknown')], max_length=20)),
                ('response_customer', models.CharField(blank=True, max_length=100)),
                ('response_note', models.CharField(blank=True, max_length=300)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('owner_accepted', models.BooleanField(null=True)),
                ('owner_acted_at', models.DateTimeField(blank=True, null=True)),
                ('compliance_noted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('corrective_txn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variance_correction', to='core.transaction')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variance_queries', to='core.item')),
                ('owner_action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variance_reviews', to=settings.AUTH_USER_MODEL)),
                ('queried_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variance_queries', to='accounts.userprofile')),
                ('stock_take', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variances', to='core.stocktake')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
