# Generated by Django 6.0.3 on 2026-07-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0102_stock_take_and_variance'),
    ]

    operations = [
        migrations.AddField(
            model_name='bartab',
            name='tab_pin',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
    ]
