# Generated by Django 4.2.29 on 2026-07-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0103_bartab_tab_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='bartab',
            name='cash_requested_at',
            field=models.DateTimeField(blank=True, help_text='Set when a customer taps "Lipa Cash" on their live receipt — no money has moved, this just flags staff to expect them at the counter. Cleared the moment staff settles any entry on the tab.', null=True),
        ),
    ]
