# Generated by Django 4.2.29 on 2026-07-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0104_bartab_cash_requested'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bartab',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'OPEN'), models.Q(('tab_pin', ''), _negated=True)), fields=('business', 'tab_pin'), name='unique_open_tab_pin_per_business'),
        ),
    ]
