# Generated by Django 4.2.29 on 2026-07-20 23:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0047_alter_userprofile_role'),
        ('core', '0105_bartab_unique_open_tab_pin_per_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesResetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name_cache', models.CharField(blank=True, max_length=255)),
                ('performed_by_username_cache', models.CharField(blank=True, max_length=150)),
                ('reason', models.TextField(blank=True)),
                ('counts_snapshot', models.JSONField(default=dict, help_text='Per-model row counts captured immediately before delete')),
                ('backup_filename', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_reset_logs', to='accounts.business')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_resets_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
