# Generated by Django 4.2.29 on 2026-07-21 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0047_alter_userprofile_role'),
        ('core', '0106_salesresetlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogUploadBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('rows_total', models.IntegerField(default=0)),
                ('rows_parsed', models.IntegerField(default=0)),
                ('rows_skipped', models.IntegerField(default=0)),
                ('skipped_examples', models.JSONField(default=list, help_text='Capped sample of unparseable raw row text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_upload_batches', to='accounts.business')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catalog_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierCatalogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('raw_name', models.CharField(blank=True, max_length=200)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('volume_ml', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=30)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('default_reorder_level', models.IntegerField(default=0)),
                ('default_reorder_quantity', models.IntegerField(default=0)),
                ('presets_json', models.JSONField(default=list, help_text='Same shape as the static catalog entries’ "presets" key')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_catalog_entries', to='accounts.business')),
                ('source_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.cataloguploadbatch')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
