# Generated by Django 4.2.29 on 2026-07-21 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_cataloguploadbatch_suppliercatalogentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='awarded_bid',
            field=models.ForeignKey(blank=True, help_text='Set when this PO was auto-created from a procurement award — the only prior link was a free-text note in `notes`.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='core.supplierbid'),
        ),
    ]
