# Generated by Django 4.2.29 on 2026-07-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0108_purchaseorder_awarded_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='debt_settled',
            field=models.BooleanField(default=False, help_text="True once this payment's debt/receipt settlement (entry-selection mode, debt-block mode, or staff-initiated debt STK) has been processed (by callback or JS poll)."),
        ),
    ]
