# Generated by Django 4.2.29 on 2026-07-21 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0048_business_last_daily_summary_sent_at'),
        ('core', '0109_payment_debt_settled'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='source_catalog_entry',
            field=models.ForeignKey(blank=True, help_text='Set when this item was created via the "Add from Catalogue" bulk-add screen from an uploaded supplier entry. Gives the price-variance report an exact match instead of relying on fuzzy name matching. Items created any other way (manually, or from the static catalogue) are matched by name at report time instead.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='core.suppliercatalogentry'),
        ),
        migrations.CreateModel(
            name='SupplierCatalogEntryPriceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('applied', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed', models.BooleanField(default=False)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_price_logs', to='accounts.business')),
                ('dismissed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_logs', to='core.suppliercatalogentry')),
                ('source_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_changes', to='core.cataloguploadbatch')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
