# Generated by Django 4.2.29 on 2026-07-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_catalog_price_variance'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Null for items that existed before this field was added (2026-07-22) — treated as "old enough" wherever this is used for that reason. Added specifically so fresh_stock_count_checklist can tell a pre-reset item (needs recounting) apart from one created after the reset (never had anything to reconcile in the first place).', null=True),
        ),
    ]
