# Generated by Django 4.2.29 on 2026-07-22 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_item_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='raw_material_source',
            field=models.ForeignKey(blank=True, help_text="Kitchen batch items only: the raw-material Item this batch is drawn from (e.g. Chipo → Potatoes (Raw)). When set, opening a new KitchenBatch draws kg from this item's own tracked balance instead of a typed cost guess — cost_total is derived automatically and the sack's remaining balance stays visible on Kitchen Board, separate from whether today's batch is done. Leave unset to keep the original manual cost-entry flow.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_batch_items', to='core.item'),
        ),
        migrations.AddField(
            model_name='kitchenbatch',
            name='source_item',
            field=models.ForeignKey(blank=True, help_text="Raw-material item this batch's cost was drawn from, if opened via the sack-tracking flow (item.raw_material_source set). Null for batches opened with a manually typed cost.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kitchen_batches_drawn', to='core.item'),
        ),
        migrations.AddField(
            model_name='kitchenbatch',
            name='source_qty_drawn',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Quantity drawn from source_item to open this batch, if applicable.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Receipt', 'Receipt'), ('Issue', 'Issue'), ('Wastage', 'Wastage'), ('OwnerConsumption', 'Owner Consumption'), ('Draw', 'Kitchen Batch Draw')], max_length=20),
        ),
    ]
