# Generated by Django 4.2.29 on 2026-07-23 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_business_last_daily_summary_sent_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0112_item_raw_material_source_kitchenbatch_source_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabTransferRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=80)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tab_transfer_requests', to='accounts.business')),
                ('dest_tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests_in', to='core.bartab')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to='core.bartabentry')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tab_transfer_requests_made', to=settings.AUTH_USER_MODEL)),
                ('source_tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests_out', to='core.bartab')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
