# Generated by Django 4.2.29 on 2026-07-23 22:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0113_tabtransferrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabtransferrequest',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Snapshot of what the source customer paid themselves at split time (e.g. Roy\'s 50 of an 80 KES cup) — captured here so the pending banner and any later debt-reasoning note can say "X already paid Y himself" without a fragile join back to the sibling entry that was reduced at split time.', max_digits=10),
        ),
    ]
