# Generated by Django 4.2.29 on 2026-07-23 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0114_tabtransferrequest_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='performersession',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='performersession',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='performersession',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performer_sessions_cancelled', to=settings.AUTH_USER_MODEL),
        ),
    ]
