# Generated by Django 4.2.29 on 2026-07-24 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0115_performersession_cancel_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableorder',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tableorder',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tableorder',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_orders_cancelled', to=settings.AUTH_USER_MODEL),
        ),
    ]
