# Generated by Django 4.2.29 on 2026-07-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0116_tableorder_cancel_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockvariancequery',
            name='owner_note',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
