# Generated by Django 4.2.29 on 2026-07-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_stockvariancequery_owner_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabtransferrequest',
            name='batch_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Shared by every row created by one "transfer whole tab" action (2026-07-25) — blank for an ordinary single-item transfer. accept()/reject() cascade to every PENDING sibling sharing this id so a whole-tab transfer resolves as ONE decision, not one per item.', max_length=32),
        ),
    ]
