# Generated by Django 4.2.29 on 2026-07-24 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_staff_name_change_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0118_tabtransferrequest_batch_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabPaymentRevocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.CharField(max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('previous_payment_method', models.CharField(blank=True, max_length=10)),
                ('was_stk_confirmed', models.BooleanField(default=False, help_text='True if a completed Payment (Safaricom-confirmed STK) record was found for this tab at revoke time — a hint to whoever re-settles that real M-Pesa money may already be involved, shown so they check before assuming nothing was actually paid.')),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('revoked_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tab_payment_revocations', to='accounts.business')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_revocations', to='core.bartabentry')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tab_payment_revocations', to=settings.AUTH_USER_MODEL)),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_revocations', to='core.bartab')),
            ],
            options={
                'ordering': ['-revoked_at'],
            },
        ),
    ]
