# Generated by Django 4.2.29 on 2026-07-24 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0119_tabpaymentrevocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='variance_mpesa_ref',
            field=models.CharField(blank=True, help_text='M-Pesa transaction code, when the explanation was "sent the cash to M-Pesa".', max_length=40),
        ),
        migrations.AddField(
            model_name='shift',
            name='variance_note',
            field=models.CharField(blank=True, help_text="Staff's own explanation for a cash variance at close, captured via reason chips.", max_length=300),
        ),
        migrations.AddField(
            model_name='shift',
            name='variance_review_note',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='shift',
            name='variance_review_status',
            field=models.CharField(blank=True, choices=[('acknowledged', 'Acknowledged — explanation accepted'), ('flagged', 'Flagged — needs follow-up')], max_length=15),
        ),
        migrations.AddField(
            model_name='shift',
            name='variance_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shift',
            name='variance_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_variances_reviewed', to=settings.AUTH_USER_MODEL),
        ),
    ]
