# Generated by Django 4.2.29 on 2026-07-25 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_shift_variance_mpesa_ref_shift_variance_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockvariancequery',
            name='attributed_shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributed_variance_queries', to='core.shift'),
        ),
    ]
