# Generated by Django 4.2.29 on 2026-07-25 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0121_stockvariancequery_attributed_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link_url',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
