# Generated by Django 4.2.29 on 2026-07-25 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0051_business_default_credit_limit'),
        ('core', '0122_notification_link_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='KitchenStockReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(blank=True, help_text='e.g. Meatco', max_length=100)),
                ('invoice_no', models.CharField(blank=True, help_text='e.g. Order #A25533', max_length=50)),
                ('received_on', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('DONE', 'Done')], default='OPEN', max_length=10)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kitchen_stock_receipts', to='accounts.business')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kitchen_stock_receipts_closed', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kitchen_stock_receipts_recorded', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kitchen_stock_receipts', to='core.store')),
            ],
            options={
                'verbose_name': 'Kitchen Stock Receipt',
                'verbose_name_plural': 'Kitchen Stock Receipts',
                'ordering': ['-received_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='KitchenStockReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty_received', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kitchen_stock_receipt_lines', to='core.item')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.kitchenstockreceipt')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.transaction')),
            ],
            options={
                'verbose_name': 'Kitchen Stock Receipt Line',
                'verbose_name_plural': 'Kitchen Stock Receipt Lines',
                'ordering': ['id'],
            },
        ),
    ]
