# Generated by Django 4.2.29 on 2026-07-25 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0123_kitchenstockreceipt_kitchenstockreceiptline'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemportionpreset',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Per-unit cost for THIS specific cut/preset — used when several presets under one shared item (e.g. Kuku: Bawa/Paja/Kifua) are bought at genuinely different unit costs, so item.cost_price alone cannot represent them (2026-07-25, Kitchen Stock Receipt). Written ONLY by KitchenStockReceiptLine at receiving time — deliberately never editable from the item form itself (Roy's explicit instruction). Item.cost_price is left untouched for these presets and stays whatever it was.", max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='kitchenstockreceiptline',
            name='preset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kitchen_stock_receipt_lines', to='core.itemportionpreset'),
        ),
    ]
