# Generated by Django 4.2.29 on 2026-07-26 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0124_itemportionpreset_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycash',
            name='linked_expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_cash_entries', to='core.businessexpense'),
        ),
        migrations.AddField(
            model_name='pettycash',
            name='staff_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pettycash',
            name='staff_note_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='businessexpense',
            name='category',
            field=models.CharField(choices=[('labor', 'Labor / Salaries'), ('electricity', 'Electricity Bills'), ('rent', 'Rent'), ('utilities', 'Utilities (Water, Internet)'), ('transport', 'Transport / Logistics'), ('marketing', 'Marketing & Advertising'), ('maintenance', 'Maintenance & Repairs'), ('supplies', 'Office Supplies'), ('tax', 'Taxes & Licenses'), ('entertainment', 'Entertainment / DJ / MC Fees'), ('security', 'Security & Facilitation'), ('petty_cash', 'Petty Cash (Counter Drawdowns)'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='recurringexpense',
            name='category',
            field=models.CharField(choices=[('labor', 'Labor / Salaries'), ('electricity', 'Electricity Bills'), ('rent', 'Rent'), ('utilities', 'Utilities (Water, Internet)'), ('transport', 'Transport / Logistics'), ('marketing', 'Marketing & Advertising'), ('maintenance', 'Maintenance & Repairs'), ('supplies', 'Office Supplies'), ('tax', 'Taxes & Licenses'), ('entertainment', 'Entertainment / DJ / MC Fees'), ('security', 'Security & Facilitation'), ('petty_cash', 'Petty Cash (Counter Drawdowns)'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
