# Generated by Django 4.2.29 on 2026-07-26 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_business_default_credit_limit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0125_petty_cash_staff_note_and_expense_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('restock', 'Ombi la Stock'), ('permission', 'Ruhusa Maalum'), ('correction', 'Marekebisho'), ('general', 'Jambo Lingine')], default='general', max_length=20)),
                ('subject', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Inasubiri'), ('approved', 'Imeidhinishwa'), ('rejected', 'Imekataliwa')], default='pending', max_length=10)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_requests', to='accounts.business')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_requests_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_requests_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Request',
                'verbose_name_plural': 'Staff Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
