# Generated by Django 4.2.29 on 2026-07-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0126_staff_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarypayment',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='confirmed_by_staff',
            field=models.BooleanField(default=False),
        ),
    ]
