# Generated by Django 4.2.29 on 2026-07-26 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0127_salary_payment_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffrequest',
            name='related_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_requests', to='core.transaction'),
        ),
        migrations.AlterField(
            model_name='staffrequest',
            name='category',
            field=models.CharField(choices=[('restock', 'Ombi la Stock'), ('permission', 'Ruhusa Maalum'), ('correction', 'Marekebisho'), ('stock_confirm', 'Uthibitisho wa Oda'), ('general', 'Jambo Lingine')], default='general', max_length=20),
        ),
    ]
