# Generated by Django 4.2.29 on 2026-07-26 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0051_business_default_credit_limit'),
        ('core', '0128_staff_request_stock_confirm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salarypayment',
            name='payment_type',
            field=models.CharField(choices=[('full', 'Full Payment'), ('partial', 'Partial Payment'), ('advance', 'Salary Advance')], default='full', help_text="'full' = complete salary; 'partial' = instalment toward the period's salary.", max_length=10),
        ),
        migrations.CreateModel(
            name='SalaryAdvanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField()),
                ('period', models.CharField(help_text='Period this advance counts against, YYYY-MM.', max_length=7)),
                ('status', models.CharField(choices=[('pending', 'Inasubiri'), ('approved', 'Imeidhinishwa'), ('rejected', 'Imekataliwa')], default='pending', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_note', models.CharField(blank=True, max_length=300)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_advance_requests', to='accounts.business')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_advances_reviewed', to=settings.AUTH_USER_MODEL)),
                ('salary_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advance_request', to='core.salarypayment')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_advance_requests', to='accounts.userprofile')),
            ],
            options={
                'verbose_name': 'Salary Advance Request',
                'verbose_name_plural': 'Salary Advance Requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
