# Generated by Django 4.2.29 on 2026-07-27 12:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0129_salary_advance_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="pettycash",
            name="station",
            field=models.CharField(
                blank=True,
                choices=[("bar", "Bar"), ("kitchen", "Kitchen")],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="banked_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Cash removed/banked from this till between the previous shift closing and this one opening.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="expected_opening_cash",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="opening_variance",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
