# Generated by Django 4.2.29 on 2026-07-27 22:54

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0130_till_accountability"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="opening_variance_mpesa_ref",
            field=models.CharField(
                blank=True,
                help_text='M-Pesa transaction code, when the explanation was "sent/deposited to M-Pesa".',
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="opening_variance_note",
            field=models.CharField(
                blank=True,
                help_text="Staff's own explanation for an opening-cash variance, captured via reason chips.",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="opening_variance_review_note",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="shift",
            name="opening_variance_review_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("acknowledged", "Acknowledged — explanation accepted"),
                    ("flagged", "Flagged — needs follow-up"),
                ],
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="opening_variance_reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shift",
            name="opening_variance_reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shift_opening_variances_reviewed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="shift",
            name="banked_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                help_text="Net cash removed (or, if negative, added) from this till since the previous shift closed.",
                max_digits=10,
            ),
        ),
    ]
