# Generated by Django 4.2.29 on 2026-07-28 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0131_opening_variance_accountability"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="station",
            field=models.CharField(
                blank=True,
                choices=[("bar", "Bar"), ("kitchen", "Kitchen")],
                max_length=10,
            ),
        ),
    ]
