# Generated by Django 4.2.29 on 2026-07-29 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0132_shift_explicit_station"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="preset",
            field=models.ForeignKey(
                blank=True,
                help_text="Which portion preset was actually sold, e.g. 'Paja Nusu' vs 'Paja Nzima' on a shared 'Kuku' item. 2026-07-28: closes the gap flagged when per-preset cost_price was built — without this, cost() had no way to know WHICH cut was sold and fell back to the item's single blended cost_price for every preset, which breaks the moment two presets share a price (e.g. a half chicken leg and a drumstick both sold at KES 150) but have different real costs. See Transaction.cost().",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales",
                to="core.itemportionpreset",
            ),
        ),
    ]
