# Generated by Django 4.2.29 on 2026-07-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0133_transaction_preset_fk"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="shiftstockcount",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="shiftstockcount",
            name="phase",
            field=models.CharField(
                choices=[("opening", "Opening"), ("closing", "Closing")],
                default="closing",
                max_length=10,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="shiftstockcount",
            unique_together={("shift", "item", "phase")},
        ),
    ]
