# Generated by Django 4.2.29 on 2026-07-30 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0052_manager_petty_cash_shift_toggles"),
        ("core", "0134_shift_stock_count_phase"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffrequest",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                help_text='Instruction only. Blank = every staff member sees it and any one of them may complete it (a broadcast task, e.g. "everyone do a stock count today").',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_requests_assigned",
                to="accounts.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="staffrequest",
            name="direction",
            field=models.CharField(
                choices=[
                    ("request", "Ombi — kutoka kwa mfanyakazi"),
                    ("instruction", "Agizo — kutoka kwa mmiliki"),
                ],
                default="request",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="staffrequest",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="staffrequest",
            name="related_item",
            field=models.ForeignKey(
                blank=True,
                help_text="For confirm_count / receive_goods instructions about a specific item.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_requests",
                to="core.item",
            ),
        ),
        migrations.AddField(
            model_name="staffrequest",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("general", "Maelezo / Kazi Nyingine"),
                    ("stock_take", "Fanya Hesabu ya Stock"),
                    ("receive_goods", "Pokea Bidhaa"),
                    ("confirm_count", "Thibitisha Idadi ya Bidhaa"),
                ],
                default="general",
                max_length=20,
            ),
        ),
    ]
