# Generated by Django 4.2.29 on 2026-07-30 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0052_manager_petty_cash_shift_toggles"),
        ("core", "0135_staff_request_instructions"),
    ]

    operations = [
        migrations.CreateModel(
            name="TillCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "station",
                    models.CharField(
                        choices=[("bar", "Bar"), ("kitchen", "Kitchen")], max_length=10
                    ),
                ),
                (
                    "counted_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "expected_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "variance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("counted_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("note", models.CharField(blank=True, max_length=300)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="till_counts",
                        to="accounts.business",
                    ),
                ),
                (
                    "counted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="till_counts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Till Count",
                "verbose_name_plural": "Till Counts",
                "ordering": ["-counted_at"],
            },
        ),
    ]
