# Generated by Django 4.2.29 on 2026-07-31 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0136_tillcount"),
    ]

    operations = [
        migrations.AddField(
            model_name="writeoffrequest",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("writeoff", "Write-off — Deni Halisi"),
                    ("erase_mistake", "Ilikuwa Kosa — Bidhaa Haikutolewa"),
                ],
                default="writeoff",
                max_length=20,
            ),
        ),
    ]
