# Generated by Django 4.2.29 on 2026-07-31 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0137_writeoffrequest_request_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="confirmed_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this shift was actually confirmed (Thibitisha) — used by station_revenue_window_start() as the reset point for the live dashboard revenue tile, so a station's revenue keeps accruing past midnight/closing time until someone actually signs off.",
                null=True,
            ),
        ),
    ]
