# Generated by Django 4.2.29 on 2026-08-02 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0138_shift_confirmed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="shift",
            name="closed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who actually submitted the close — same as staff for an ordinary self-close, different when an owner/manager closed it on someone else's behalf.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shifts_closed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="force_close_reason",
            field=models.CharField(
                blank=True,
                help_text="Optional explanation when closed_by differs from staff — why the owner/manager closed this shift on their behalf.",
                max_length=300,
            ),
        ),
    ]
