# Generated by Django 4.2.29 on 2026-08-05 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0139_shift_closed_by_shift_force_close_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="tableorder",
            name="tab",
            field=models.ForeignKey(
                blank=True,
                help_text="The table's running tab — this order's items are billed here once SERVED. Payment (cash/mpesa/split/debt) happens by settling this tab, not at order-placement time.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="table_orders",
                to="core.bartab",
            ),
        ),
        migrations.AlterField(
            model_name="tableorder",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cash", "Cash"),
                    ("mpesa", "M-Pesa"),
                    ("credit", "Credit / Tab"),
                ],
                default="cash",
                help_text="Legacy field, kept for schema history — no longer read to set the final sale's payment method (see tab below). Payment is now decided when the table's tab is settled, not guessed at order-placement time.",
                max_length=10,
            ),
        ),
    ]
