# Generated by Django 4.2.29 on 2026-08-02 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0056_uba_store_scoping_and_plan"),
        ("core", "0141_store_uba_outlet_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transfer_number",
                    models.PositiveIntegerField(
                        help_text='Gap-free per business — same guarantee as Receipt.receipt_number. Display via .reference (e.g. "TRF-0001").'
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Rasimu"),
                            ("DISPATCHED", "Imetumwa"),
                            ("RECEIVED", "Imepokelewa"),
                            ("DISPUTED", "Ina Utata"),
                            ("CANCELLED", "Imefutwa"),
                        ],
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                ("dispatched_at", models.DateTimeField(blank=True, null=True)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_transfers",
                        to="accounts.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_created",
                        to="accounts.userprofile",
                    ),
                ),
                (
                    "dispatched_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_dispatched",
                        to="accounts.userprofile",
                    ),
                ),
                (
                    "from_store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers_out",
                        to="core.store",
                    ),
                ),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_received",
                        to="accounts.userprofile",
                    ),
                ),
                (
                    "rider",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transfers_ridden",
                        to="accounts.userprofile",
                    ),
                ),
                (
                    "to_store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers_in",
                        to="core.store",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("business", "transfer_number")},
            },
        ),
        migrations.CreateModel(
            name="StockTransferLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty_sent", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "qty_received",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                ("variance_note", models.CharField(blank=True, max_length=200)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.item"
                    ),
                ),
                (
                    "transfer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="core.stocktransfer",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="transaction",
            name="transfer",
            field=models.ForeignKey(
                blank=True,
                help_text="UBA §5.2 — set on both legs of a stock transfer between stores (the dispatch Issue and the receive Receipt). Discriminator that excludes a transfer from revenue()/cost() everywhere — a transfer is a stock movement, never a sale.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transactions",
                to="core.stocktransfer",
            ),
        ),
    ]
