# Generated by Django 4.2.29 on 2026-08-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0142_stocktransfer_stocktransferline_transaction_transfer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="type",
            field=models.CharField(
                choices=[
                    ("Receipt", "Receipt"),
                    ("Issue", "Issue"),
                    ("Wastage", "Wastage"),
                    ("OwnerConsumption", "Owner Consumption"),
                    ("Draw", "Kitchen Batch Draw"),
                    ("Transfer", "Stock Transfer Between Stores"),
                ],
                max_length=20,
            ),
        ),
    ]
