# Generated by Django 4.2.29 on 2026-08-02 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0056_uba_store_scoping_and_plan"),
        ("core", "0143_alter_transaction_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessException",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("shrinkage", "Upungufu wa Bidhaa"),
                            ("cash_variance", "Tofauti ya Fedha"),
                            ("transfer_dispute", "Utata wa Uhamisho"),
                            ("below_cost", "Bei Chini ya Gharama"),
                            ("credit_blocked", "Deni kwa Mteja Aliyezuiliwa"),
                            ("no_sales", "Hakuna Mauzo"),
                            ("stock_count_variance", "Tofauti ya Hesabu ya Stock"),
                            ("till_not_counted", "Till Haijahesabiwa"),
                            ("other", "Nyingine"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Taarifa"),
                            ("warn", "Onyo"),
                            ("danger", "Hatari"),
                        ],
                        default="info",
                        max_length=10,
                    ),
                ),
                (
                    "amount_kes",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("detail", models.TextField(blank=True)),
                ("link_url", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exceptions_acknowledged",
                        to="accounts.userprofile",
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exceptions",
                        to="accounts.business",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exceptions",
                        to="core.shift",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exceptions_caused",
                        to="accounts.userprofile",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exceptions",
                        to="core.store",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
