# Generated by Django 4.2.29 on 2026-08-02 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0057_business_contribute_market_data_and_more"),
        ("core", "0144_businessexception"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "barcode",
                    models.CharField(db_index=True, max_length=32, unique=True),
                ),
                ("name", models.CharField(max_length=160)),
                ("brand", models.CharField(blank=True, max_length=80)),
                (
                    "pack_size",
                    models.CharField(
                        blank=True,
                        help_text="e.g. '250g', '500ml', '2kg'",
                        max_length=40,
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=20)),
                ("category", models.CharField(blank=True, max_length=60)),
                ("image_url", models.URLField(blank=True)),
                (
                    "confirm_count",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="How many different businesses have agreed on this name.",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="True once confirm_count >= 3."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contributed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="global_products_contributed",
                        to="accounts.business",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="item",
            name="balance_confirmed_at",
            field=models.DateTimeField(
                blank=True,
                help_text='When this item\'s on-hand balance was last established by a real physical count — set by adjust_stock_balance() (Rekebisha) every time it runs, and by the first-ever Receipt on a brand-new item (fast onboarding: "Anza bila kuhesabu" never demands an opening balance, so an item can go a while with this blank). NULL means "never confirmed" — excluded from shrinkage attribution (would generate false accusations against staff) and surfaced honestly in stock_list as "Haijahesabiwa" rather than silently assumed.',
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="barcode",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Scanned barcode, if any. Looked up against the cross-tenant GlobalProduct dictionary — never unique per business, since the same barcode legitimately exists at many different dukas.",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="MarketPriceIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "median_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "median_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("sample_size", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "county",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.county",
                    ),
                ),
                (
                    "global_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_indexes",
                        to="core.globalproduct",
                    ),
                ),
            ],
            options={
                "unique_together": {("global_product", "county")},
            },
        ),
    ]
