# Generated by Django 4.2.29 on 2026-08-02 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0058_business_margin_alert_pct_and_more"),
        ("core", "0146_return_itempricehistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="abc_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A", "A — juu ya thamani (hesabu kila wiki)"),
                    ("B", "B — wastani (hesabu kila mwezi)"),
                    ("C", "C — chini ya thamani (hesabu kila robo mwaka)"),
                ],
                help_text="Set by core.cycle_count.classify_abc_all() from 90-day revenue contribution — top 80% of value=A, next 15%=B, rest=C. Blank until first classified.",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="is_high_risk",
            field=models.BooleanField(
                default=False,
                help_text="High value × small size (razors, batteries, phone accessories, spirits miniatures...) — force-included in every cycle count regardless of ABC class.",
            ),
        ),
        migrations.CreateModel(
            name="StockCountSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("CYCLE", "Hesabu ya kila siku"),
                            ("FULL", "Hesabu kamili"),
                            ("SPOT", "Hesabu ya ghafla"),
                        ],
                        default="CYCLE",
                        max_length=6,
                    ),
                ),
                (
                    "scope_note",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'Class A — 12 items'",
                        max_length=100,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("OPEN", "Wazi"), ("CLOSED", "Imefungwa")],
                        default="OPEN",
                        max_length=6,
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_count_sessions",
                        to="accounts.business",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.shift",
                    ),
                ),
                (
                    "started_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.userprofile",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.store",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="StockCountLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "book_qty",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Snapshot at count time — never recomputed later.",
                        max_digits=12,
                    ),
                ),
                (
                    "counted_qty",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                (
                    "variance_qty",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                (
                    "variance_kes",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="'imeharibika' | 'imeibiwa' | 'kosa la kuandika' | ...",
                        max_length=100,
                    ),
                ),
                ("counted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "attributed_shift",
                    models.ForeignKey(
                        blank=True,
                        help_text="Which shift is believed accountable for this variance — see core.cycle_count.record_count_line(), reuses shift_views.attribute_variance_shift().",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.shift",
                    ),
                ),
                (
                    "counted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.userprofile",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.item"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="core.stockcountsession",
                    ),
                ),
            ],
        ),
    ]
