# Generated by Django 4.2.29 on 2026-08-02 08:20

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0058_business_margin_alert_pct_and_more"),
        ("core", "0147_item_abc_class_item_is_high_risk_stockcountsession_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "supplier_name",
                    models.CharField(
                        blank=True,
                        help_text="Off-platform distributor name — most cases.",
                        max_length=200,
                    ),
                ),
                ("invoice_no", models.CharField(blank=True, max_length=60)),
                (
                    "invoice_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DUE", "Inadaiwa"),
                            ("PARTIAL", "Imelipwa Kiasi"),
                            ("PAID", "Imelipwa"),
                            ("DISPUTED", "Ina Utata"),
                        ],
                        default="DUE",
                        max_length=10,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_invoices",
                        to="accounts.business",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="supplier_invoices",
                        to="core.purchaseorder",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.userprofile",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.store",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        help_text="A platform supplier, if this business trades with one via the marketplace.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_invoices",
                        to="accounts.business",
                    ),
                ),
            ],
            options={
                "ordering": ["due_date", "-invoice_date"],
            },
        ),
        migrations.CreateModel(
            name="SupplierPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("mpesa", "M-Pesa"),
                            ("bank", "Bank"),
                            ("other", "Nyingine"),
                        ],
                        default="cash",
                        max_length=10,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=100)),
                ("paid_on", models.DateField(default=django.utils.timezone.localdate)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="core.supplierinvoice",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-paid_on"],
            },
        ),
    ]
