# Generated by Django 4.2.29 on 2026-08-02 08:33

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0059_business_layaway_forfeit_pct_and_more"),
        ("core", "0148_supplierinvoice_supplierpayment"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("LAYAWAY", "Lipa pole pole"),
                            ("DEPOSIT", "Amana"),
                            ("INSTALMENT", "Malipo ya awamu"),
                            ("BOOKING", "Booking"),
                        ],
                        default="LAYAWAY",
                        max_length=12,
                    ),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "hold_expires_on",
                    models.DateField(
                        blank=True,
                        help_text="Layaway: goods held until this date.",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Wazi"),
                            ("COMPLETED", "Imekamilika"),
                            ("FORFEITED", "Amana Imepotea"),
                            ("REFUNDED", "Imerejeshwa"),
                            ("CANCELLED", "Imefutwa"),
                        ],
                        default="OPEN",
                        max_length=10,
                    ),
                ),
                (
                    "forfeit_policy",
                    models.CharField(
                        blank=True,
                        help_text="Human-readable, snapshotted from Business.layaway_forfeit_policy at creation time and shown on the deposit receipt — never retro-applied if the business setting changes later.",
                        max_length=200,
                    ),
                ),
                (
                    "reserved_qty",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_plans",
                        to="accounts.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.userprofile",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_plans",
                        to="core.customer",
                    ),
                ),
                (
                    "reserved_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_plan_reservations",
                        to="core.item",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.store",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentPlanEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("mpesa", "M-Pesa"),
                            ("other", "Nyingine"),
                        ],
                        default="cash",
                        max_length=10,
                    ),
                ),
                ("mpesa_ref", models.CharField(blank=True, max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="core.paymentplan",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.receipt",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
