# Generated by Django 4.2.29 on 2026-08-02 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0059_business_layaway_forfeit_pct_and_more"),
        ("core", "0149_paymentplan_paymentplanentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_variant_parent",
            field=models.BooleanField(
                default=False,
                help_text="A display-grouping-only row — never sold directly.",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variants",
                to="core.item",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="variant_attrs",
            field=models.JSONField(
                blank=True, default=dict, help_text="e.g. {'size':'M','colour':'Navy'}."
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="variant_label",
            field=models.CharField(
                blank=True, help_text="e.g. 'M / Navy'.", max_length=60
            ),
        ),
        migrations.AddField(
            model_name="producebunch",
            name="grade",
            field=models.CharField(
                blank=True,
                help_text="Mitumba grading: '1st'|'2nd'|'3rd'.",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="producebunch",
            name="kind",
            field=models.CharField(
                choices=[
                    ("produce", "Mboga/Matunda"),
                    ("bale", "Bale ya mitumba"),
                    ("carcass", "Nyama"),
                    ("sack", "Gunia"),
                ],
                default="produce",
                help_text="Same revenue-envelope maths for every kind — only the vocabulary/label shown to the owner should differ per business profile, never the maths.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="producebunch",
            name="label",
            field=models.CharField(
                blank=True,
                help_text="e.g. 'Bale ya jeans — Gikomba 28/07'.",
                max_length=60,
            ),
        ),
        migrations.CreateModel(
            name="FittingRoomLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pieces_out", models.PositiveIntegerField(default=0)),
                ("pieces_back", models.PositiveIntegerField(default=0)),
                ("note", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fitting_room_logs",
                        to="accounts.business",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.shift",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.userprofile",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.store",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
