# Generated by Django 4.2.29 on 2026-08-02 08:53

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0059_business_layaway_forfeit_pct_and_more"),
        ("core", "0150_item_is_variant_parent_item_parent_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(blank=True, max_length=200)),
                ("customer_phone", models.CharField(blank=True, max_length=20)),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("BOOKED", "Imewekwa"),
                            ("CONFIRMED", "Imethibitishwa"),
                            ("ARRIVED", "Amefika"),
                            ("IN_SERVICE", "Inaendelea"),
                            ("DONE", "Imekamilika"),
                            ("NO_SHOW", "Hakuja"),
                            ("CANCELLED", "Imefutwa"),
                        ],
                        default="BOOKED",
                        max_length=12,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("walkin", "Walk-in"),
                            ("phone", "Simu"),
                            ("whatsapp", "WhatsApp"),
                            ("online", "Mtandaoni"),
                        ],
                        default="walkin",
                        max_length=10,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="accounts.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="appointments_created",
                        to="accounts.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["start_at"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "category",
                    models.CharField(
                        blank=True, help_text="'Nywele'|'Kucha'|'Ngozi'.", max_length=60
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("duration_minutes", models.PositiveIntegerField(default=30)),
                ("buffer_minutes", models.PositiveIntegerField(default=0)),
                (
                    "commission_type",
                    models.CharField(
                        choices=[
                            ("NONE", "Hakuna"),
                            ("PERCENT", "Asilimia"),
                            ("FIXED", "Kiasi Maalum"),
                        ],
                        default="NONE",
                        max_length=10,
                    ),
                ),
                (
                    "commission_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                ("requires_booking", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "rebook_after_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="UBA §9.3 rebooking nudge — e.g. 42 for a 6-week retouch cycle.",
                        null=True,
                    ),
                ),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="accounts.business",
                    ),
                ),
                (
                    "shadow_item",
                    models.OneToOneField(
                        blank=True,
                        help_text="Auto-created — see core.salon.get_or_create_shadow_item(). Never sold via the normal item-balance path; its own balance is meaningless/untracked.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_for",
                        to="core.item",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.store",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="customer",
            name="no_show_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="UBA §9.3 (Salon) — missed appointments. A repeat no-show can be required to leave a booking deposit (PaymentPlan kind=BOOKING).",
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="performed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="UBA §9.2 (Salon) — the STYLIST who performed the service, distinct from `recorded_by` (the cashier/whoever rang it up). Never set for non-salon sales.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="services_performed",
                to="accounts.userprofile",
            ),
        ),
        migrations.CreateModel(
            name="ServiceSupplyLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qty_expected",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="e.g. 60 (ml of relaxer).",
                        max_digits=10,
                    ),
                ),
                (
                    "tolerance_pct",
                    models.DecimalField(
                        decimal_places=1,
                        default=Decimal("25.0"),
                        help_text="Hair varies — be generous or you cry wolf.",
                        max_digits=5,
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        help_text="A MEASURE or UNIT stock item.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.item",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplies",
                        to="core.service",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AppointmentService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price_at_booking",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="core.appointment",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.service"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="appointment",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="core.customer",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="deposit_plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.paymentplan",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="staff",
            field=models.ForeignKey(
                blank=True,
                help_text="Requested stylist.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="accounts.userprofile",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.store"
            ),
        ),
        migrations.AddField(
            model_name="transaction",
            name="service",
            field=models.ForeignKey(
                blank=True,
                help_text="UBA §9.2 (Salon) — set on the shadow-item Issue transaction when this is a completed service sale, and on each recipe-line supply deduction.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales",
                to="core.service",
            ),
        ),
    ]
