# Generated by Django 4.2.29 on 2026-08-02 09:03

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0060_alter_userprofile_role"),
        ("core", "0151_appointment_service_customer_no_show_count_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RentalUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("property", "Nyumba/Chumba"), ("equipment", "Kifaa")],
                        default="property",
                        max_length=10,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="'A12' — doubles as the M-Pesa Paybill account number.",
                        max_length=30,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, help_text="'Bedsitter A12'.", max_length=120
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "default_rate",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Per month (property) or per day (equipment).",
                        max_digits=12,
                    ),
                ),
                (
                    "rate_period",
                    models.CharField(
                        choices=[("day", "Siku"), ("week", "Wiki"), ("month", "Mwezi")],
                        default="month",
                        max_length=6,
                    ),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Equipment: 300 chairs = one unit, qty 300.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Iko wazi"),
                            ("RESERVED", "Imewekwa"),
                            ("OCCUPIED", "Ina mtu"),
                            ("OUT", "Imetoka"),
                            ("MAINTENANCE", "Inatengenezwa"),
                            ("RETIRED", "Imeondolewa"),
                        ],
                        default="AVAILABLE",
                        max_length=12,
                    ),
                ),
                ("is_metered", models.BooleanField(default=False)),
                (
                    "is_published",
                    models.BooleanField(
                        default=False, help_text="Storefront listing (Phase 6)."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rental_units",
                        to="accounts.business",
                    ),
                ),
                (
                    "store",
                    models.ForeignKey(
                        blank=True,
                        help_text="Property/portfolio.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.store",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
                "unique_together": {("business", "code")},
            },
        ),
        migrations.CreateModel(
            name="RentalAgreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("rate", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "rate_period",
                    models.CharField(
                        choices=[("day", "Siku"), ("week", "Wiki"), ("month", "Mwezi")],
                        default="month",
                        max_length=6,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1, help_text="e.g. 200 of the 300 chairs."
                    ),
                ),
                (
                    "deposit_held",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                ("billing_day", models.PositiveSmallIntegerField(default=5)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Rasimu"),
                            ("ACTIVE", "Inaendelea"),
                            ("ENDED", "Imeisha"),
                            ("TERMINATED", "Imesitishwa"),
                        ],
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                ("terms_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rental_agreements",
                        to="accounts.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.userprofile",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        help_text="Tenant/hirer — reuses debt + credit score.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rental_agreements",
                        to="core.customer",
                    ),
                ),
                (
                    "deposit_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.paymentplan",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agreements",
                        to="core.rentalunit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MeterReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("water", "Maji"), ("electricity", "Umeme")],
                        max_length=15,
                    ),
                ),
                ("reading", models.DecimalField(decimal_places=2, max_digits=12)),
                ("read_on", models.DateField(default=django.utils.timezone.localdate)),
                (
                    "rate_per_unit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "read_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.userprofile",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meter_readings",
                        to="core.rentalunit",
                    ),
                ),
            ],
            options={
                "ordering": ["-read_on"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Wazi"),
                            ("IN_PROGRESS", "Inashughulikiwa"),
                            ("CLOSED", "Imefungwa"),
                        ],
                        default="OPEN",
                        max_length=12,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounts.userprofile",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounts.userprofile",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_tickets",
                        to="core.rentalunit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RentalInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("rent_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "utilities_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "other_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                ("other_note", models.CharField(blank=True, max_length=200)),
                ("total", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                ("due_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DUE", "Inadaiwa"),
                            ("PARTIAL", "Imelipwa Kiasi"),
                            ("PAID", "Imelipwa"),
                            ("WAIVED", "Imesamehewa"),
                        ],
                        default="DUE",
                        max_length=10,
                    ),
                ),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="core.rentalagreement",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.receipt",
                    ),
                ),
                (
                    "rent_txn",
                    models.ForeignKey(
                        blank=True,
                        help_text='UBA §10.3 — the credit Transaction the debt tracker actually reads. "Arrears ARE debt" — no parallel aging engine; see core.rentals.py.',
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.transaction",
                    ),
                ),
            ],
            options={
                "ordering": ["due_date"],
                "unique_together": {("agreement", "period_start")},
            },
        ),
    ]
