# Generated by Django 4.2.29 on 2026-08-05 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0140_tableorder_tab_alter_tableorder_payment_method"),
        ("core", "0152_rentalunit_rentalagreement_meterreading_and_more"),
    ]

    operations = []
