# Generated by Django 4.2.29 on 2026-08-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0153_merge_20260806_0029"),
    ]

    operations = [
        migrations.AddField(
            model_name="tableorder",
            name="station",
            field=models.CharField(
                blank=True,
                choices=[("bar", "Bar"), ("kitchen", "Kitchen")],
                max_length=10,
            ),
        ),
    ]
