# Generated by Django 4.2.29 on 2026-08-07 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0155_bartabentry_settled_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="settles_transaction",
            field=models.ForeignKey(
                blank=True,
                help_text="2026-08-07 live request — 'no way for the owner to pay for what he was given through Mmiliki Alichukua'. Set ONLY on the real, revenue-bearing Issue transaction (qty=0 — the stock already left at consumption time, this only records money coming in) created when an OwnerConsumption draw is settled — points back at the original draw. Presence of any row in `<draw>.settlements` IS the paid flag; no separate boolean needed. Generic field name/self-FK (not owner-consumption-specific) in case a future settlement flow needs the same shape.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="settlements",
                to="core.transaction",
            ),
        ),
    ]
