# Generated by Django 4.2.29 on 2026-08-08 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0156_transaction_settles_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemportionpreset",
            name="tracks_stock_of",
            field=models.ForeignKey(
                blank=True,
                help_text='This preset is a different-sized cut of the SAME physical lot as the preset pointed to here — e.g. "Half Chicken Leg" tracks_stock_of "Full Chicken Leg" (a full leg cut and sold as two halves is still one leg out of what was received). 2026-08-09 live request: without this, a preset that was never itself received under its own name (only its "parent" cut was) either shows as permanently out of stock, or sells invisibly without ever decrementing the parent cut\'s own received-vs-sold tally. Blank = counts against itself (the default, unchanged behavior for every preset that doesn\'t need this). Set from Edit Item, existing presets only.',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tracked_by",
                to="core.itemportionpreset",
            ),
        ),
    ]
