# Generated by Django 4.2.29 on 2026-08-09 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0157_itemportionpreset_tracks_stock_of"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessexpense",
            name="recorded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenses_recorded",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="businessexpense",
            name="station",
            field=models.CharField(
                blank=True,
                choices=[("bar", "Bar"), ("kitchen", "Kitchen")],
                max_length=10,
            ),
        ),
    ]
