# Generated by Django 4.2.29 on 2026-08-11 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0158_businessexpense_station_recorded_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pettycash",
            name="reason",
            field=models.CharField(
                choices=[
                    ("electricity", "Electricity / Tokens"),
                    ("supplies", "Supplies (tissues, serviettes, etc.)"),
                    ("transport", "Transport / Delivery"),
                    ("fuel", "Fuel / Gas"),
                    ("food", "Staff Meal"),
                    (
                        "cash_disbursement",
                        "Fedha kwa Mtu (polisi, chama, n.k.) — SI gharama ya biashara",
                    ),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
