# Generated by Django 4.2.29 on 2026-08-11 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0159_alter_pettycash_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="kegbarrel",
            name="closed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who closed this barrel — deplete_barrel() (Imekwisha) or discard() (Tupa), whichever happened.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="kegs_closed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="kegbarrel",
            name="tapped_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Who tapped (opened) this barrel — 2026-08-11 live request (Roy): visible on the tile alongside received_by, same accountability trail this app already keeps for every other stock action.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="kegs_tapped",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
