# Generated by Django 4.2.29 on 2026-08-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0160_kegbarrel_closed_by_kegbarrel_tapped_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="itemportionpreset",
            name="restock_anchor_at",
            field=models.DateTimeField(
                blank=True,
                help_text="A pure TILE-VISIBILITY cursor — never touches revenue, cost, or transaction history. When set, the received-vs-sold \"Iliyobaki\" tally for this preset (see kitchen_board()) only counts receiving and sales dated on/after this point, ignoring anything earlier — even genuinely-preserved old history the owner deliberately kept. 2026-08-12 live request (Roy, Monsoon Inn): the received/sold tally is otherwise a true LIFETIME sum with no cutoff at all; a tether (tracks_stock_of) added after old sales already happened retroactively pulls those old sales into the anchor's running total the moment the tether exists, permanently suppressing a fresh restock's \"remaining\" even when Roy explicitly does NOT want that old history deleted (Kitchen Item Reset's own destructive wipe is the wrong tool for this — it would erase real revenue history he wants to keep). Stamped automatically by Kitchen Item Reset's confirm step on the item's own anchor presets (never on a tethered preset's own field — stock_tracking_anchor_id() never resolves to one). Blank = today's exact lifetime-sum behavior, unchanged, for every preset that has never been through a reset.",
                null=True,
            ),
        ),
    ]
