# Generated by Django 4.2.29 on 2026-08-12 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0062_userprofile_can_adjust_stock_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0161_itemportionpreset_restock_anchor_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="OwnerConsumptionTransferRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("to_owner", "To Owner"),
                            ("from_owner", "From Owner"),
                        ],
                        max_length=10,
                    ),
                ),
                ("dest_customer_name", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=80)),
                (
                    "batch_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Shared by every row created by one whole-bill transfer — blank for a single-item transfer. accept()/reject() cascade to every PENDING sibling sharing this id.",
                        max_length=32,
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner_consumption_transfer_requests",
                        to="accounts.business",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owner_consumption_transfer_requests_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "source_txn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner_transfer_requests",
                        to="core.transaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
            },
        ),
    ]
