# Generated by Django 4.2.29 on 2026-08-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0162_ownerconsumptiontransferrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="is_owner_alias",
            field=models.BooleanField(
                default=False,
                help_text='2026-08-13 live request (Roy): this Customer record is actually the business owner, recorded under a name (e.g. "Bosco") that also happens to be his own — NOT automatic name-matching (see Mmiliki Alichukua\'s own design note on why that\'s deliberately avoided elsewhere), only ever set via the explicit owner/manager-confirmed "🔗 Weka kama Mmiliki" action on this customer\'s own debt profile. Once set, that action becomes a "🔄 Sawazisha kwa Mmiliki" resync button — every currently-unpaid debt transaction under this exact customer record is proposed (still via the normal pending/accept step, never auto-moved) to the owner\'s own OwnerConsumption ledger each time it\'s pressed, so debt that accumulates under this name later doesn\'t silently pile up unnoticed. Also read by tab_check_api to warn staff typing a SIMILAR (not exact) name at checkout — "is this the same person as the owner?" — rather than guessing.',
            ),
        ),
    ]
