# Generated by Django 4.2.29 on 2026-08-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0163_customer_is_owner_alias"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="was_credit",
            field=models.BooleanField(
                default=False,
                help_text="2026-08-15 live report (Roy, Monsoon Inn) — 'Total Paid' exceeding 'Total Credit' on the debt tracker, with genuinely-still-owed items silently vanishing from 'Unpaid Credit Transactions'. Root cause: core.debt_views._get_customer_debt_data()'s 'Total Credit' figure summed transactions LIVE-filtered on payment_method=='credit' right now — but at least ~15 separate settle paths (tick_entry, settle_tab, settle_entries_amount_locked, the STK-push tab-settlement callbacks, and _do_settle_debt_payment's own FIFO reconciliation among them) all flip payment_method AWAY from 'credit' the instant a transaction is resolved — correct for shift_views._reconcile()'s cash/mpesa/credit split, but it meant the debt tracker's own 'Total Credit' silently SHRANK by that same amount the moment ANY of those paths resolved a transaction, while CustomerDebtPayment ('Total Paid', append-only) never shrank to match — eventually producing Paid > Credit and 'all paid' showing on customers who genuinely still owed money. This field is the fix: a permanent, one-way marker (never cleared once set) stamped automatically the moment payment_method transitions AWAY from 'credit' on an EXISTING row (see __init__/save() below) — _get_customer_debt_data()'s 'Total Credit' now sums was_credit=True OR still-currently-credit transactions, making it a stable historical total that can never shrink out from under total_paid again. Achieved at the model layer specifically so it automatically covers every one of those ~15 existing (and any future) settle call sites with zero changes needed to any of them — a naive per-view sweep risked missing one, exactly the failure mode that caused this bug in the first place.",
            ),
        ),
    ]
