# Generated by Django 4.2.29 on 2026-08-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0166_exchange"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kitchenbatch",
            name="note",
            field=models.TextField(blank=True),
        ),
    ]
