# Generated by Django 4.2.29 on 2026-08-18 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0167_alter_kitchenbatch_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerdebtpayment",
            name="revert_reason",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="customerdebtpayment",
            name="reverted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customerdebtpayment",
            name="reverted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customerdebtpayment",
            name="reverted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="debt_payments_reverted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
