# Generated by Django 4.2.29 on 2026-08-21 08:05

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0063_userprofile_can_revert_debt_payment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0168_customerdebtpayment_revert_reason_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PortioningEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qty_drawn",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1"), max_digits=10
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portioning_events",
                        to="accounts.business",
                    ),
                ),
                (
                    "draw_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Portioning Event",
                "verbose_name_plural": "Portioning Events",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AlterField(
            model_name="item",
            name="raw_material_source",
            field=models.ForeignKey(
                blank=True,
                help_text="The raw-material Item this item is drawn from. For a Kitchen batch item (e.g. Chipo → Potatoes (Raw)), opening a new KitchenBatch draws kg from this item's own tracked balance instead of a typed cost guess — cost_total is derived automatically. Since 2026-08-21 (Gawa Kuku) also used for a plain portion item whose presets are cuts of a whole raw unit (e.g. Kuku → Whole Chicken) — see PortioningEvent. Either way the raw item's remaining balance stays visible on Kitchen Board, separate from whether today's batch/cut is done. Leave unset to keep the original manual cost-entry flow.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derived_batch_items",
                to="core.item",
            ),
        ),
        migrations.CreateModel(
            name="PortioningEventLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qty_produced", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cost_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="core.portioningevent",
                    ),
                ),
                (
                    "preset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="portioning_event_lines",
                        to="core.itemportionpreset",
                    ),
                ),
                (
                    "receipt_transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="core.transaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Portioning Event Line",
                "verbose_name_plural": "Portioning Event Lines",
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="portioningevent",
            name="finished_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="portioning_events_as_finished",
                to="core.item",
            ),
        ),
        migrations.AddField(
            model_name="portioningevent",
            name="raw_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="portioning_events_as_raw",
                to="core.item",
            ),
        ),
        migrations.AddField(
            model_name="portioningevent",
            name="recorded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="portioning_events_recorded",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="portioningevent",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="portioning_events",
                to="core.store",
            ),
        ),
    ]
