# Generated by Django 4.2.29 on 2026-08-21 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0169_portioningevent_alter_item_raw_material_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="split_from",
            field=models.ForeignKey(
                blank=True,
                help_text="2026-08-21 live report (Roy — \"will backdating, gawanya and all other relevant functions to sales change and adjust the receipt\"): set ONLY on the NEW sibling row split_payment_method_locked() creates for a split-off remainder — points back at the transaction it was carved out of. A direct-sale receipt line has no way to know a sale was later split (the sibling never gets its own receipt line — the receipt may already be issued by the time a Gawanya correction happens); core.receipt_views._live_direct_lines() uses this to synthesize the missing line and refresh the parent line's now-stale subtotal, live, at render time. Only one level deep by design — splitting an already-split-off sibling a second time is a documented, accepted limitation (its own grandchild split_from would point at the sibling, not the receipt's own original line id).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="split_children",
                to="core.transaction",
            ),
        ),
    ]
