# Generated by Django 4.2.29 on 2026-08-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0170_transaction_split_from"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shiftstockcount",
            name="phase",
            field=models.CharField(
                choices=[
                    ("opening", "Opening"),
                    ("closing", "Closing"),
                    ("midshift", "Mid-shift"),
                ],
                default="closing",
                max_length=10,
            ),
        ),
    ]
