# Generated by Django 4.2.29 on 2026-08-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0171_shiftstockcount_midshift_phase"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockvariancequery",
            name="gap_note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="stockvariancequery",
            name="kind",
            field=models.CharField(
                choices=[("shift", "Shift-Attributed"), ("gap", "Unattended-Gap")],
                default="shift",
                max_length=10,
            ),
        ),
    ]
