# Generated by Django 4.2.29 on 2026-08-23 10:17

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0064_can_record_expenses"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0172_stockvariancequery_gap_note_stockvariancequery_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="ledger_token",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="2026-08-23 (Roy): stable public token for this customer's own transaction+payment ledger page, embedded as an \"Angalia historia yako\" link in their debt-reminder SMS. Generated lazily on first use (see core.customer_profile.ensure_ledger_token) so no migration has to backfill every existing customer. Same security model as a receipt token — the unguessable URL is the proof of identity, and it only ever reaches that customer's own phone.",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="DebtReminderLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("manual", "Sent by staff"),
                            ("auto_flag", "Auto-sent before defaulter flag"),
                        ],
                        default="manual",
                        max_length=12,
                    ),
                ),
                (
                    "outstanding_at_send",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "delivered",
                    models.BooleanField(
                        default=False,
                        help_text='False when the reminder could not be sent at all (no phone on file, unnormalisable number, or the SMS gateway rejected it). Logged either way — "we tried and could not reach them" is itself part of the trail, and a missing phone must never block a business decision.',
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debt_reminders",
                        to="accounts.business",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="debt_reminders",
                        to="core.customer",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="debt_reminders_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Debt Reminder",
                "verbose_name_plural": "Debt Reminders",
                "ordering": ["-sent_at"],
            },
        ),
    ]
