# Generated by Django 4.2.29 on 2026-08-23 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0065_userprofile_consumption_limit_amount_and_more"),
        ("core", "0173_customer_ledger_token_debtreminderlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="consumed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="2026-08-23 (Roy): WHICH owner took this draw. Only ever set for type='OwnerConsumption' — recorded_by is whoever KEYED the entry in (routinely a staff member), which is a different question and cannot stand in for it. Needed because owner consumption limits are held per owner, so a business with more than one owner can give each their own ceiling. Null on every pre-2026-08-23 draw and on any business that never picks an owner, in which case the limit check falls back to the business's single owner where there is exactly one.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owner_consumption_draws",
                to="accounts.userprofile",
            ),
        ),
    ]
