# Generated by Django 4.2.29 on 2026-08-23 16:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0174_transaction_consumed_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="bartabentry",
            name="debt_collected_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=10
            ),
        ),
    ]
