# Generated by Django 4.2.29 on 2026-08-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0175_bartabentry_debt_collected_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockvariancequery",
            name="dispute_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stockvariancequery",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Staff Response"),
                    ("responded", "Staff Responded"),
                    ("disputed", "Rejected as Theft — Appeal Window Open"),
                    ("resolved", "Resolved"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
