# Generated by Django 4.2.29 on 2026-08-26 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0176_stockvariancequery_dispute_deadline_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemportionpreset",
            name="cost_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Per-whole-unit cost for THIS specific cut/preset (same basis as item.cost_price, NOT a per-fraction price) — used when several presets under one shared item (e.g. Kuku: Bawa/Paja/Kifua) are bought at genuinely different unit costs, so item.cost_price alone cannot represent them (2026-07-25, Kitchen Stock Receipt). Historically written ONLY by KitchenStockReceiptLine at receiving time — deliberately never editable from the item form itself (Roy's explicit instruction). 2026-08-26 (Roy — \"the cost price division should be according to preset\"): a SECOND, narrow writer — stock_take_views.review_variance()'s increase-accept flow — also sets this, but only when an INCREASE stock-take variance lands on a fraction matching this exact preset's quantity_consumed (see _matching_preset_for_increase()); item.cost_price is left untouched in that case too, same as the kitchen writer.",
                max_digits=12,
                null=True,
            ),
        ),
    ]
