# Generated by Django 4.2.29 on 2026-09-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0177_alter_itemportionpreset_cost_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="bartabentry",
            name="written_off_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
