# Generated by Django 6.0 on 2026-03-23 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('staff', 'Staff')], default='staff', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.business'),
        ),
    ]
