# Generated by Django 6.0 on 2026-03-23 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_role_alter_userprofile_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='sub_location',
        ),
    ]
