# Generated by Django 6.0 on 2026-03-23 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_business_sub_location'),
        ('core', '0008_subcounty_ward_delete_sublocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='sub_county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.subcounty'),
        ),
        migrations.AddField(
            model_name='business',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.ward'),
        ),
    ]
