# Generated by Django 4.2.29 on 2026-04-08 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_business_id_alter_userprofile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='closing_time',
            field=models.TimeField(blank=True, help_text='e.g. 18:00', null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Flat delivery fee in KES', max_digits=10),
        ),
        migrations.AddField(
            model_name='business',
            name='delivery_radius_km',
            field=models.DecimalField(decimal_places=1, default=5, help_text='Max delivery distance in km', max_digits=5),
        ),
        migrations.AddField(
            model_name='business',
            name='is_open_override',
            field=models.BooleanField(blank=True, default=None, help_text='Manual override: True=force open, False=force closed, None=use hours', null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='min_order_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum order value in KES', max_digits=10),
        ),
        migrations.AddField(
            model_name='business',
            name='offers_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='business',
            name='opening_time',
            field=models.TimeField(blank=True, help_text='e.g. 08:00', null=True),
        ),
    ]
