# Generated by Django 4.2.29 on 2026-04-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_business_closing_time_business_delivery_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('staff', 'Staff'), ('rider', 'Rider')], default='staff', max_length=10),
        ),
    ]
