# Generated by Django 4.2.29 on 2026-04-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='mpesa_paybill',
            field=models.CharField(blank=True, help_text='Paybill Business Number', max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='mpesa_paybill_account',
            field=models.CharField(blank=True, help_text='Paybill Account Number', max_length=50),
        ),
        migrations.AddField(
            model_name='business',
            name='mpesa_phone',
            field=models.CharField(blank=True, help_text='Personal M-Pesa phone number for receiving', max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='mpesa_pochi',
            field=models.CharField(blank=True, help_text='Pochi la Biashara phone number', max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='mpesa_till',
            field=models.CharField(blank=True, help_text='Lipa Na M-Pesa Till Number (Buy Goods)', max_length=20),
        ),
        migrations.AddField(
            model_name='business',
            name='preferred_payment_channel',
            field=models.CharField(blank=True, choices=[('till', 'Till Number (Buy Goods)'), ('paybill', 'Paybill'), ('pochi', 'Pochi la Biashara'), ('phone', 'Personal M-Pesa')], help_text='Default payment channel customers should use', max_length=10),
        ),
    ]
