# Generated by Django 4.2.29 on 2026-04-10 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_business_mpesa_paybill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='delivery_fee_per_km',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Additional fee per km', max_digits=10),
        ),
        migrations.AddField(
            model_name='business',
            name='min_order_per_km',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Additional minimum per km of distance', max_digits=10),
        ),
        migrations.AlterField(
            model_name='business',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base delivery fee in KES', max_digits=10),
        ),
        migrations.AlterField(
            model_name='business',
            name='min_order_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base minimum order in KES', max_digits=10),
        ),
        migrations.CreateModel(
            name='DeliveryTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('foot', '🚶 On Foot'), ('bicycle', '🚲 Bicycle'), ('boda', '🏍️ Boda Boda'), ('vehicle', '🚗 Vehicle')], max_length=15)),
                ('max_distance_km', models.DecimalField(decimal_places=1, help_text='Max range for this mode in km', max_digits=5)),
                ('base_fee', models.DecimalField(decimal_places=2, default=0, help_text='Base fee for this mode', max_digits=10)),
                ('fee_per_km', models.DecimalField(decimal_places=2, default=0, help_text='Additional fee per km', max_digits=10)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_tiers', to='accounts.business')),
            ],
            options={
                'ordering': ['max_distance_km'],
                'unique_together': {('business', 'mode')},
            },
        ),
    ]
