# Generated by Django 4.2.29 on 2026-04-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_delivery_tiers_and_distance_pricing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('staff', 'Staff'), ('rider', 'Rider'), ('supplier', 'Supplier')], default='staff', max_length=10),
        ),
    ]
