# Generated by Django 4.2.29 on 2026-04-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_add_supplier_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_seen_tutorial',
            field=models.BooleanField(default=False),
        ),
    ]
