# Generated by Django 4.2.29 on 2026-04-11 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_add_has_seen_tutorial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDeletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('role', models.CharField(max_length=20)),
                ('business_name', models.CharField(blank=True, max_length=255)),
                ('reason', models.CharField(choices=[('not_useful', 'The platform is not useful for my business'), ('too_complex', 'Too complex / hard to use'), ('found_alternative', 'Found a better alternative'), ('closing_business', 'Closing my business'), ('privacy', 'Privacy / data concerns'), ('temporary', 'Just taking a break'), ('other', 'Other')], max_length=30)),
                ('details', models.TextField(blank=True, help_text='Optional additional details')),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-deleted_at'],
            },
        ),
    ]
