# Generated by Django 4.2.29 on 2026-04-11 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_add_account_deletion_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('sw', 'Kiswahili'), ('ki', 'Gĩkũyũ'), ('luo', 'Dholuo'), ('kln', 'Kalenjin'), ('kam', 'Kĩkamba'), ('luy', 'Luhya'), ('guz', 'Ekegusii'), ('mer', 'Kĩmĩrũ'), ('mas', 'Maa (Maasai)'), ('tuv', "Ng'aturkana"), ('so', 'Soomaali'), ('dav', 'Kitaita'), ('pko', 'Pokot'), ('teo', 'Ateso'), ('saq', 'Samburu'), ('ebu', 'Kĩembu')], default='en', max_length=5),
        ),
    ]
