# Generated by Django 6.0.3 on 2026-04-14 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_add_preferred_language'),
        ('core', '0023_importjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='businesses', to='core.category'),
        ),
    ]
