# Generated by Django 4.2.29 on 2026-05-22 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_business_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_start_date',
            field=models.DateField(blank=True, help_text='When did this business first open? Used to show the full break-even timeline including pre-app history.', null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='pre_app_cumulative_profit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Total profit earned before starting to use Duka Mwecheche. Used to give accurate break-even calculations for existing businesses.', max_digits=14),
        ),
    ]
