# Generated by Django 6.0.3 on 2026-06-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_add_pre_app_profit_and_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='credit_window_days',
            field=models.PositiveIntegerField(default=30, help_text='Maximum days a customer debt may remain outstanding before it is flagged as overdue.'),
        ),
    ]
