# Generated by Django 6.0.3 on 2026-06-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_debt_tracker_and_targets'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_sections_seen',
            field=models.JSONField(blank=True, default=list, help_text='List of section IDs whose product tour has been seen. e.g. ["dashboard", "stores", "items"]'),
        ),
    ]
