# Generated by Django 6.0.3 on 2026-06-03 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_add_onboarding_sections_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_input_cost_price',
            field=models.BooleanField(default=False, help_text='Staff can input cost price when receiving goods. They see the input field but never the previous cost price.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_override_restrictions',
            field=models.BooleanField(default=False, help_text='Staff can sell restricted items without triggering an owner approval request.'),
        ),
    ]
