# Generated by Django 6.0.3 on 2026-06-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_add_staff_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='last_txn_sms_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last transaction SMS sent. Used for 10-minute bundling window.', null=True),
        ),
    ]
