# Generated by Django 6.0.3 on 2026-06-13 15:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_business_keg_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='keg_revenue_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.50'), help_text='Suggested barrel target = cost × this. 5000 × 1.5 = 7500, matching common owner targets.', max_digits=4),
        ),
    ]
