# Generated by Django 6.0.3 on 2026-06-13 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_business_keg_revenue_multiplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('staff', 'Staff'), ('waitress', 'Waitress / Waiter'), ('rider', 'Rider'), ('supplier', 'Supplier')], default='staff', max_length=10),
        ),
    ]
