# Generated by Django 6.0.3 on 2026-06-14 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_add_waitress_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='last_expense_review_date',
            field=models.DateField(blank=True, help_text='Date owner last reviewed and confirmed recurring expenses.', null=True),
        ),
    ]
