# Generated by Django 6.0.3 on 2026-06-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_recurring_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='daraja_c2b_registered',
            field=models.BooleanField(default=False, help_text='True once C2B confirmation URL has been registered with Safaricom'),
        ),
        migrations.AddField(
            model_name='business',
            name='daraja_consumer_key',
            field=models.CharField(blank=True, help_text='Safaricom Daraja API Consumer Key for this business shortcode', max_length=200),
        ),
        migrations.AddField(
            model_name='business',
            name='daraja_consumer_secret',
            field=models.CharField(blank=True, help_text='Safaricom Daraja API Consumer Secret for this business shortcode', max_length=200),
        ),
    ]
