# Generated by Django 6.0.3 on 2026-06-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_business_daraja_environment'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='has_kitchen',
            field=models.BooleanField(default=False, help_text='Enable the Kitchen / Grill module. Auto-creates a Kitchen store on first enable.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('staff', 'Staff'), ('waitress', 'Waitress / Waiter'), ('kitchen', 'Kitchen / Grill Staff'), ('rider', 'Rider'), ('supplier', 'Supplier')], default='staff', max_length=10),
        ),
    ]
