# Generated by Django 6.0.3 on 2026-06-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_business_has_kitchen_role_kitchen'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_access_bar',
            field=models.BooleanField(default=False, help_text='Kitchen staff may access the Bar Board. Grant if they also serve bar customers.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='can_access_kitchen',
            field=models.BooleanField(default=True, help_text='Bar/general staff may access the Kitchen Board. Revoke if you want them bar-only.'),
        ),
    ]
