# Generated by Django 6.0.3 on 2026-06-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_userprofile_cross_module_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='kitchen_requires_shift',
            field=models.BooleanField(default=False, help_text='Kitchen staff must open a shift before they can work. Off by default — kitchen staff normally bypass shift enforcement.'),
        ),
    ]
