# Generated by Django 6.0.3 on 2026-06-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_userprofile_kitchen_requires_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='can_access_kitchen',
            field=models.BooleanField(default=False, help_text='Bar/general staff may access the Kitchen Board. Off by default — grant explicitly.'),
        ),
    ]
