# Generated by Django 6.0.3 on 2026-06-25 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_business_keg_alerts'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='keg_loss_baseline_pct',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Cached average loss % learned from fully-depleted barrels with weight readings.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='keg_loss_baseline_sample',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Number of depleted barrels in the current baseline sample.', null=True),
        ),
    ]
