# Generated by Django 6.0.3 on 2026-06-25 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_business_keg_baseline'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='kra_pin',
            field=models.CharField(blank=True, default='', help_text='KRA PIN for eTIMS invoice submission (e.g. P051234567M). Leave blank until eTIMS integration is live.', max_length=20),
        ),
    ]
