# Generated by Django 6.0.3 on 2026-06-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_business_kra_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_receive_kitchen_stock',
            field=models.BooleanField(default=False, help_text='Kitchen staff may receive stock (Pata Stok) on the kitchen board. Off by default — grant explicitly when owner trusts staff with stock intake.'),
        ),
    ]
