# Generated by Django 6.0.3 on 2026-06-26 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_userprofile_can_receive_kitchen_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='haki_enabled',
            field=models.BooleanField(default=True, help_text='Enable the Haki staff contribution + salary transparency module.'),
        ),
    ]
