# Generated by Django 6.0.3 on 2026-06-27 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_barrel_depletion_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='cup_low_notified_at',
            field=models.DateTimeField(blank=True, help_text='Last time a cup low-stock alert was fired. Reset when new cups are logged.', null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='cups_per_jug',
            field=models.PositiveIntegerField(default=6, help_text='Physical disposable cups consumed per jug serving (shared at a table). Default 6 — a 2L jug split between 6 people. Adjust to match your typical group size.'),
        ),
        migrations.AddField(
            model_name='business',
            name='cups_per_pint',
            field=models.PositiveIntegerField(default=0, help_text='Physical disposable cups consumed per pint serving. 0 = served in glass/mug. Set to 1 if your bar pours pints into disposable cups.'),
        ),
    ]
