# Generated by Django 6.0.3 on 2026-06-27 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_barcuplog_business_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='cups_per_jug',
            field=models.PositiveIntegerField(default=6, help_text='How many 300ml cups are used per jug — whether to measure the pour (e.g. 3 cups = 900ml) or serve customers at the table. Set to 3 if you fill 3 cups to measure before pouring a jug.'),
        ),
        migrations.AlterField(
            model_name='business',
            name='cups_per_pint',
            field=models.PositiveIntegerField(default=0, help_text='How many 300ml cups are used per pint — whether to measure the pour, serve the customer, or both. 0 = served in a glass or mug (no cups used).'),
        ),
    ]
