# Generated by Django 6.0.3 on 2026-06-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_cups_helptext'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='event_sms_enabled',
            field=models.BooleanField(default=False, help_text='SMS the owner when a DJ/MC session is started by counter staff.'),
        ),
        migrations.AddField(
            model_name='business',
            name='performer_approval_threshold',
            field=models.PositiveIntegerField(default=0, help_text='Sessions with agreed_fee >= this value require owner approval before going ACTIVE. 0 = disabled (all sessions start immediately).'),
        ),
    ]
