# Generated by Django 6.0.3 on 2026-07-05 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_performer_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_authorize_tab_accumulation',
            field=models.BooleanField(default=False, help_text='Staff may approve tab orders for customers who already have outstanding debt. Owner-only by default.'),
        ),
    ]
