# Generated by Django 6.0.3 on 2026-07-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_can_authorize_tab_accumulation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('staff', 'Staff'), ('waitress', 'Waitress / Waiter'), ('kitchen', 'Kitchen / Grill Staff'), ('rider', 'Rider'), ('supplier', 'Supplier')], default='staff', max_length=10),
        ),
    ]
