# Generated by Django 4.2.29 on 2026-07-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='last_daily_summary_sent_at',
            field=models.DateTimeField(blank=True, help_text="Timestamp of the last daily summary SMS/email sent. Prevents a duplicate cron fire or retry from re-sending the same day's summary.", null=True),
        ),
    ]
