# Generated by Django 4.2.29 on 2026-07-24 02:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0048_business_last_daily_summary_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='departed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='departed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_departures_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='departure_note',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='departure_reason',
            field=models.CharField(blank=True, choices=[('resigned', 'Alijiuzulu mwenyewe'), ('terminated', 'Aliachishwa kazi'), ('transferred', 'Alihamishiwa tawi lingine'), ('end_of_contract', 'Mkataba uliisha'), ('other', 'Nyingine')], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_reactivations_recorded', to=settings.AUTH_USER_MODEL),
        ),
    ]
