# Generated by Django 4.2.29 on 2026-07-24 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0049_userprofile_departure_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffNameChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_username', models.CharField(blank=True, max_length=150)),
                ('new_username', models.CharField(blank=True, max_length=150)),
                ('old_display_name', models.CharField(blank=True, max_length=200)),
                ('new_display_name', models.CharField(blank=True, max_length=200)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_name_changes', to='accounts.business')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_name_changes_made', to=settings.AUTH_USER_MODEL)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_change_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
