# Generated by Django 4.2.29 on 2026-07-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_staff_name_change_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='default_credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Business-wide default max outstanding credit (KES) applied to every customer who has no limit of their own set on their profile. Blank = no default limit (a customer with no per-customer limit either can borrow without a KES cap, subject to the other credit policy gates). A per-customer limit on Customer.credit_limit always overrides this default for that one customer.', max_digits=10, null=True),
        ),
    ]
