# Generated by Django 4.2.29 on 2026-07-30 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0051_business_default_credit_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="can_confirm_shifts",
            field=models.BooleanField(
                default=False,
                help_text="Manager may confirm (Thibitisha) a CLOSED shift for staff/waitress/kitchen roles. Does not extend to a manager's own shift, or another manager's shift — those always require the owner to confirm.",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_review_petty_cash",
            field=models.BooleanField(
                default=False,
                help_text="Manager may approve/reject petty cash entries. Owner-only by default. A manager can never review their own submitted entry regardless of this flag.",
            ),
        ),
    ]
