# Generated by Django 4.2.29 on 2026-07-31 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0052_manager_petty_cash_shift_toggles"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="debt_erase_requires_approval",
            field=models.BooleanField(
                default=False,
                help_text="2026-07-31 — for a genuinely mistaken debt-section entry (wrong item/customer, not a real uncollectable debt), staff can mark it 'Ilikuwa Kosa' to restore stock the same way removing a tab entry already does. Default False = self-service (any staff with an open shift can execute it immediately, matching the tab-side Futa behavior). True = the same request goes through owner/manager approval first (see UserProfile.can_approve_debt_erase) before stock is restored — an owner-activated opt-in for tighter oversight, not the default.",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_approve_debt_erase",
            field=models.BooleanField(
                default=False,
                help_text="Manager may approve/reject a debt-section 'Ilikuwa Kosa' (mistaken entry) erase request when Business.debt_erase_requires_approval is enabled. Owner-only by default. Never extends to a real Write-off (uncollectable debt) request — that final decision always requires the owner.",
            ),
        ),
    ]
