# Generated by Django 4.2.29 on 2026-07-31 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0053_business_debt_erase_requires_approval_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="can_receive_stock",
            field=models.BooleanField(
                default=True,
                help_text="Staff may record a Receipt (stock-in) via Add Transaction — the bar/general stock intake flow, and Quick Sell's own \"+ Pata Stok\" shortcut, which share this one gate. On by default (matches how every business has always worked); revoke for a specific staff member the owner does not trust to log deliveries accurately. Owner and manager are always exempt from this gate. Distinct from can_receive_kitchen_stock, which is the kitchen board's own separate toggle.",
            ),
        ),
    ]
