# Generated by Django 4.2.29 on 2026-08-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0054_userprofile_can_receive_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountdeletionlog",
            name="reason",
            field=models.CharField(
                choices=[
                    ("not_useful", "The platform is not useful for my business"),
                    ("too_complex", "Too complex / hard to use"),
                    ("found_alternative", "Found a better alternative"),
                    ("closing_business", "Closing my business"),
                    ("privacy", "Privacy / data concerns"),
                    ("temporary", "Just taking a break"),
                    ("other", "Other"),
                    ("admin_removed", "Removed by platform admin"),
                ],
                max_length=30,
            ),
        ),
    ]
