# Generated by Django 4.2.29 on 2026-08-02 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0056_uba_store_scoping_and_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="contribute_market_data",
            field=models.BooleanField(
                default=True,
                help_text="Share product NAMES, barcodes and pack sizes (never prices) into the cross-tenant GlobalProduct dictionary when adding a new item by barcode. On by default — opt out any time; never shares this business's prices either way.",
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="contribute_price_data",
            field=models.BooleanField(
                default=False,
                help_text="Opt-IN only. Lets this business's cost/selling prices feed the county-level MarketPriceIndex benchmark (median only, sample_size>=5, never a single business's figure) — and, in exchange, lets this business SEE that benchmark. Opting out loses the benchmark, not just the contribution.",
            ),
        ),
    ]
