# Generated by Django 4.2.29 on 2026-08-02 08:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0057_business_contribute_market_data_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="margin_alert_pct",
            field=models.DecimalField(
                decimal_places=1,
                default=Decimal("15.0"),
                help_text="A supplier cost rise beyond this percentage (vs the item's previous cost) fires a cost_rise BusinessException + owner alert with a suggested new selling price that preserves the old margin ratio.",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="return_approval_threshold",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="A customer return whose refund exceeds this KES amount needs owner/manager approval before stock/revenue are reversed. Blank means every return auto-processes regardless of amount.",
                max_digits=12,
                null=True,
            ),
        ),
    ]
