# Generated by Django 4.2.29 on 2026-08-02 08:33

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0058_business_margin_alert_pct_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="layaway_forfeit_pct",
            field=models.DecimalField(
                decimal_places=1,
                default=Decimal("10.0"),
                help_text="Admin fee percentage deducted on forfeit, when layaway_forfeit_policy=minus_percent.",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="layaway_forfeit_policy",
            field=models.CharField(
                choices=[
                    ("full_refund", "Rejesha Yote"),
                    ("minus_percent", "Rejesha Kiasi (toa asilimia)"),
                    ("full_forfeit", "Haitarejeshwa Kabisa"),
                ],
                default="minus_percent",
                help_text="What happens to a layaway deposit if the customer never completes the plan. Default: refund minus an admin fee — never a silent full-forfeit default.",
                max_length=15,
            ),
        ),
    ]
