# Generated by Django 4.2.29 on 2026-08-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0059_business_layaway_forfeit_pct_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("manager", "Manager"),
                    ("staff", "Staff"),
                    ("waitress", "Waitress / Waiter"),
                    ("kitchen", "Kitchen / Grill Staff"),
                    ("rider", "Rider"),
                    ("supplier", "Supplier"),
                    ("caretaker", "Caretaker"),
                ],
                default="staff",
                max_length=10,
            ),
        ),
    ]
