# Generated by Django 4.2.29 on 2026-08-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0060_alter_userprofile_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="can_manage_kegs",
            field=models.BooleanField(
                default=False,
                help_text="2026-08-11 live request (Roy — a barrel physically ran out mid-shift with no owner present): staff may tap (open) a sealed barrel and mark a TAPPED barrel as done (Imekwisha/deplete) on the Bar Board. Owner/manager-only by default — grant explicitly for a specific staffer trusted to run the keg counter without the owner physically there. Does NOT extend to editing a barrel's cost/target (Hariri) or writing one off as spoiled/wrong delivery (Tupa) — those stay owner/manager-only real financial-loss decisions. Still requires the staffer to have an open shift, same as every other staff stock action.",
            ),
        ),
    ]
