# Generated by Django 4.2.29 on 2026-08-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0061_userprofile_can_manage_kegs"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="can_adjust_stock",
            field=models.BooleanField(
                default=False,
                help_text='2026-08-11 live request (Roy — "in the event the manager or business owner is not around"): staff may use ⚖️ Rekebisha on Stock List to correct an item\'s balance to a real physical count. Owner/manager-only by default. Still requires the staffer to have an open shift. Never extends the "sio hasara halisi" (not-a-real-loss) judgment call — that checkbox stays hidden for a delegated staffer even when this is on; only owner/manager ever gets to decide a shortage doesn\'t count as a real loss.',
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="can_convert_tabs_to_debt",
            field=models.BooleanField(
                default=False,
                help_text="2026-08-11 live request (Roy): a waitress may never PLACE new credit directly (that rule is unchanged — every checkout surface still blocks her outright), but with this on she may convert an existing open tab's unpaid balance to debt (Geuza Deni / bulk shift-close conversion) — the goods are already served either way; this only affects who gets to record that it happened. Off by default. Has no effect for any role other than waitress, since every other role can already do this.",
            ),
        ),
    ]
