# Generated by Django 4.2.29 on 2026-08-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0062_userprofile_can_adjust_stock_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="can_revert_debt_payment",
            field=models.BooleanField(
                default=False,
                help_text="2026-08-18 live request (Roy — \"staff recorded a debt mistakenly when it was not paid for\"): staff or manager may revert (undo) a recorded debt payment — restoring the customer's outstanding balance and correctly removing the amount from that day's cash/mpesa till figures. Owner/manager-only by default; grant explicitly to a specific staffer or manager to let them self-correct without waiting for the owner. Distinct from can_approve_debt_erase (that toggle is for erasing a debt that was never real; this one is for un-recording a payment that was never actually received).",
            ),
        ),
    ]
