# Generated by Django 4.2.29 on 2026-08-21 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0063_userprofile_can_revert_debt_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="can_record_expenses",
            field=models.BooleanField(
                default=False,
                help_text='2026-08-21 live request (Roy, on-site at Monsoon Inn — "the staff have no way of back dating expenses... I have been left with lots of recordings"): staff may record an ad-hoc/backdated expense (Matumizi ya Leo) on the Bar/Kitchen board. Owner/manager-only by default. record_ad_hoc_expense() already supports backdating via its date field — the gap was pure ACCESS, not the backdating capability itself. Correcting an already-recorded entry (edit_ad_hoc_expense) stays owner/manager-only, matching the same higher-tier-for-corrections pattern as can_manage_kegs not extending to Hariri/Tupa. Still requires the staffer to have an open shift.',
            ),
        ),
    ]
