# Generated by Django 4.2.29 on 2026-08-23 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0064_can_record_expenses"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="consumption_limit_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text='2026-08-23 live request (Roy): "Owner consumption accountability — set an amount and a window period limit setting to enhance owner discipline ... if the limit is reached and a customer takes a drink in his name the system rejects automatically." Blank means no limit at all (the default, so nothing changes for a business that never sets one). Held PER OWNER rather than on Business because Roy asked for multiple owners to be able to carry different settings — "mostly the owner is just one in these bars, regardless set it up for multiple owners just in case."',
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="consumption_limit_window",
            field=models.CharField(
                choices=[
                    ("daily", "Kila siku"),
                    ("weekly", "Kila wiki"),
                    ("monthly", "Kila mwezi"),
                ],
                default="monthly",
                help_text="Window the limit above is measured over. Ignored when no limit is set.",
                max_length=8,
            ),
        ),
    ]
