# Generated by Django 4.2.29 on 2026-08-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0065_userprofile_consumption_limit_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="variance_dispute_window_hours",
            field=models.PositiveIntegerField(
                default=48,
                help_text="2026-08-26 — when the owner rejects a stock-take variance as deliberate/malicious rather than an innocent mistake, the accused staffer gets this many hours to respond and explain before the verdict becomes permanent (affecting their recognition score and Haki record). The owner can also confirm the verdict immediately without waiting ('Thibitisha Sasa'). This window only gates the STAFF consequence — the stock correction itself and the item's availability for sale both happen immediately, regardless of this setting.",
            ),
        ),
    ]
