# Generated by Django 4.2.29 on 2026-08-27 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0067_userprofile_can_affirm_stock_take"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="last_seen_at",
            field=models.DateTimeField(
                blank=True,
                help_text='2026-08-27 live report (Roy): the home dashboard\'s "Manager on Duty" strip was driven purely by User.last_login >= start-of-today — a manager who logged in at 03:21 and left 12 hours ago still showed as "on duty" all day, since Django tracks login time only, never logout/idle time. Stamped by SingleSessionMiddleware on every authenticated request, throttled to once per ACTIVITY_STALE_MINUTES via a queryset .update() (never a full save()) to avoid adding write load on top of the already-documented SESSION_SAVE_EVERY_REQUEST disk-activity concern (see CLAUDE.md\'s 2026-08-11 502-incident entries). home()\'s active_managers query now reads this instead of last_login, so a manager silently drops off the strip once idle past the threshold rather than showing a stale same-day login timestamp indefinitely.',
                null=True,
            ),
        ),
    ]
